### ISSUE TITLE
Include relative_url_root in generated paths.

### ISSUE THREAD

**Issue by tokenshift** [railsware/js-routes#128]
I have an app that is hosted alongside several others on the same host at different paths (e.g. /app1, /app2, /app3). Rails' route helpers are configured to include the application base path with the relative_url_root setting (http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root); the URLs that js-routes constructs should include this path as well.

**Comment by le0pard** [comment]
No response, close it.
