### ISSUE TITLE
Include .gpg signature

### ISSUE THREAD

**Issue by karanmilan** [railsware/js-routes#129]
ruby-js-routes source: debian-watch-may-check-gpg-signature
 
    This watch file does not include a means to verify the upstream tarball using cryptographic signature.
   
    If upstream distributions provide such signatures, please use the
    pgpsigurlmangle options in this watch file's opts= to generate the URL of an upstream GPG signature. This signature is automatically downloaded and verified against a keyring stored in debian/upstream-signing-key.asc.
    
    Of course, not all upstreams provide such signatures, but you could request them as a way of verifying that no third party has modified the code against their wishes after the release. Projects such as phpmyadmin, unrealircd, and proftpd have suffered from this kind of attack.
    
    Refer to the uscan(1) manual page for details.
    
    Severity: pedantic, Certainty: certain
    
    Check: watch-file, Type: source

**Comment by bogdan** [comment]
Agree with @le0pard. There is no reason for such a signature.
