### ISSUE TITLE
Routes not working in jquery ajax requests

### ISSUE THREAD

**Issue by ricardopacheco** [railsware/js-routes#141]
I'm trying to run a ajax in a js file that is being called correctly in application.js and is returning an error.

I'm loading the js-routes file at the top of application.js and want to call Routes.specified_root within an anonymous function:
```javascript
$.fn.extend ({
   autoSave: function (data) {
   $ .ajax ({
       type: "POST"
       url: Routes.specified_root (params)
....
```
Uncaught TypeError: undefined is not a function

Already add the statement $.extend(window, Routes); in application.js. When the page opens in the console and type "Routes" (without quotes) it appears the object with the routes normally.
Am I doing something wrong? I followed to the letter the documentation and apparently seems all ok.

I am using jquery 2.0.3 and 1.0.0 js-routes with rails 4.2.0 and ruby 2.2.0. Sorry for my bad english ;D

**Comment by le0pard** [comment]
Did you check, what keys have `Routes` object in Browser dev console?

**Comment by ricardopacheco** [comment]
yes @le0pard, instead of using Routes.specified_root tried just now only specified_root:

Uncaught ReferenceError: save_draft_new_blog_paper_path is not defined

Look return when I type Routes in the console:

Routes
Object {clients_path: function, service_path: function, service_task_path: function, service_tasks_path: function, services_path: function…}

$.fn.extend({
  anyFunction: function () {
    code hehe,
    }
  },
  autoSave: function(data) {
    $.ajax({
      type: "POST",
      url: Routes.specified_root(1),
      dataType: "json",
      data: data,
      success: function(){
        alert("Ajax succefully!")
      }
    });
    setTimeout(function(){ console.log("Save Draft!") }, 5000);
  }
});

**Comment by le0pard** [comment]
Do you use `compact` mode? Because as I can see you have standard `*_path` routes, but you trying to get `specified_root` without "path" at the end?

**Comment by ricardopacheco** [comment]
yes!

**Comment by le0pard** [comment]
Looks like resolved

**Comment by ricardopacheco** [comment]
Not working @le0pard

**Comment by le0pard** [comment]
@ricardopacheco use autocomplete in dev console. I think, your key just not exist in object: http://monosnap.com/image/6AmaBTyhqk6sCewXtyiBJ62ftTWPkS

**Comment by ricardopacheco** [comment]
Dev console is works, Routes in another js file inside application.js is not work!

**Comment by le0pard** [comment]
If in dev console available object, this mean `Routes` object exist in `window` object and all works fine from js-routes side. I am not sure, how you check js-routes not inside application.js.

**Comment by ricardopacheco** [comment]
Order javascript calls:

<script src="/assets/js-routes.js?body=1"></script>
<script src="/assets/modernizr/modernizr.js?body=1"></script>
<script src="/assets/jquery/jquery.js?body=1"></script>
<script src="/assets/jquery-ujs/src/rails.js?body=1"></script>
<script src="/assets/underscore/underscore.js?body=1"></script>
<script src="/assets/angular/angular.js?body=1"></script>

**Comment by ricardopacheco** [comment]
@le0pard solved!

In application.js:

```javascript
$(function(){
  jQuery.extend(window, Routes)
});
```

**Comment by ibnukamy** [comment]
Hi there. I'm having a similar problem, I'm trying to access `Routes` in my javascript file (which is required by `application.js` by `require_tree .`. I'm able to acess `jQuery` from there but not `Routes`. I tried to put this in application.js but nothing changed.:
```
$(function(){
  jQuery.extend(window, Routes)
});
```

I'm also able to access `Routes' form dev console, meaning that `Routes` was already attached to the `window` even before i put the above code.
