### ISSUE TITLE
ActiveAdmin routes not excluded

### ISSUE THREAD

**Issue by thom-nic** [railsware/js-routes#145]
I'm trying to exclude some routes and for some reason ActiveAdmin routes are still included.  

my app_routes.js.erb:
```
<%= JsRoutes.generate(namespace: "Routes", exclude: [/^admin/, /^rails/, /^sidekiq/] ) %>
```

routes.rb:
```ruby
Rails.application.routes.draw do
  ActiveAdmin.routes self
  # ... 
```

... And the generated JS routes:
![admin_routes](https://cloud.githubusercontent.com/assets/95562/7139619/3a671a04-e295-11e4-8e95-47676a4c78af.png)

Maybe this has something to do with how ActiveAdmin defines its routes? All my other intended routes are included, and `/rails` and `/sidekiq` *are* properly excluded.  Apologies if I'm missing something.

Version details:
```
$ bundle show js-routes
/Users/thom/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/js-routes-1.0.0
$ bundle show activeadmin
/Users/thom/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-41043fa9aecc
$ bin/rails --version
Rails 4.2.0
```

**Comment by bogdan** [comment]
/^admin/ is a regexp that doesn't match `batch_action_admin_users_path`. You need to build more advanced regexp `/(before_action_)?admin/` or just keep it simple `/admin/` - in this way all routes with "admin" inside will be excluded.

**Comment by le0pard** [comment]
Hello, @thom-nic . You can use two regexp: `[/^admin_/, /_admin_/]`

**Comment by thom-nic** [comment]
Ah so that is matching the "path name?"  I assumed the regex was matching the actual URL path e.g. `/admin/organizations/batch_action`.  That makes sense then.  Thanks guys!
