### ISSUE TITLE
Support for routes recognition

### ISSUE THREAD

**Issue by fabn** [railsware/js-routes#147]
This gem is super awesome for generating url, but what about routes recognition?

It would be useful to have something like

```ruby
# in config/routes.rb
resource :users
```

```javascript
// when url is /users/1/edit
var a = Routes.parse(window.location)
console.log(a) // something like {controller: 'users', action: 'edit', id: 1}
```

**Comment by le0pard** [comment]
I think for this need to use another lib. This gem just generate routes.

**Comment by bogdan** [comment]
Why do you do it in ruby while Rails does it excellently and passing data from rails to JS is easy?

**Comment by fabn** [comment]
@bogdan for the same reason one could write 

```ruby
content_tag(:span, 'something', class: 'foo', data: {path: user_path(user)})
```
and then in jQuery or similar

```js
$('.foo').data('path'); // => /users/1
// Instead of 
Routes.users_path(id)
```

My primary use case is to retrieve controller params from url (for an angularjs service) especially current ids. So instead of having a dom element which only purpose is to carry `params[:id]` (or whatever) I can get route params locally. It's just a companion to current functionality, when I do `Routes.users_path(id)` I have to retrieve the id somewhere in js, this feature would make this easier.

For the moment I'm experimenting with a dedicated controller which simply do the following

```ruby
# Returns recognized param in the url given in params[:url]
def info
  respond_with(Rails.application.routes.recognize_path(params[:url]))
end
```
But this introduces the complexity of using async behavior when I need to parse route params:
```js
$.getJSON(Routes.info_path({url: window.location.href})).done(function (params) {
  // params contain current routing parameters
});
```

**Comment by bogdan** [comment]
I see your point, but I see a big difference from routes generation in JS:


Route generation can be done up to 100 times on a page. It leads to many places where you would need that `data: {path: }` etc. While as from your use case: you need to recognise path only 1 time on a page, making it significantly easier. You can even return those recognised parameters as a response header for each request, making the handing super unified: never called explicitly: just take parameters from the last response header (if it caused URL change which you can also track globally) and you are OK.

**Comment by fabn** [comment]
> While as from your use case: you need to recognise path only 1 time on a page, making it significantly easier. You can even return those recognised parameters as a response header for each request, making the handing super unified: never called explicitly: just take parameters from the last response header (if it caused URL change which you can also track globally) and you are OK.

That's a brilliant idea, I'll try it. :+1:  :+1:

**Comment by le0pard** [comment]
Make simple example, because we have schema in routes:

```js
var optionalParam = /\((.*?)\)/g;
var namedParam    = /(\(\?)?:\w+/g;
var splatParam    = /\*\w+/g;
var escapeRegExp  = /[\-{}\[\]+?.,\\\^$|#\s]/g;

getRouteRegexp = function(route) {
  route = route.replace(escapeRegExp, '\\$&')
                   .replace(optionalParam, '(?:$1)?')
                   .replace(namedParam, function(match, optional) {
                     return optional ? match : '([^/?]+)';
                   })
                   .replace(splatParam, '([^?]*?)');
  return new RegExp('^' + route + '(?:\\?([\\s\\S]*))?$');
}

var Routes = {
    some_route: function() {
        var func = function() { return "/test/22/something/23345" };
        func.toString = function() { return "/test/:id/something/:query" };
        return func;
    }()
};

alert(getRouteRegexp(Routes.some_route.toString(), Routes.some_route()).exec(Routes.some_route()).slice(1));
```

http://jsfiddle.net/ddk2vrv8/

**Comment by bogdan** [comment]
Closing this one: not enough motivation yet feel free to +1 and explain why.
