### ISSUE TITLE
Adding a comment to the top of generated files

### ISSUE THREAD

**Issue by jordanstephens** [railsware/js-routes#152]
For those of us who work on larger dev teams, it would be nice to have a comment at the top of any generated routes.js files—something which just explains that it _is_ a generated file and maybe a hint about how it is generated—so that other (and future) devs know where the file came from and also to warn anyone from trying to modify it by hand.

Perhaps this could be added as an option, so that it would not be mandatory. It would be really great to be able to do something like this:

```
config.comment = "This file was generated by the js-routes gem."
```

Would there be any interest in something like this if I put together a pull request?

**Comment by bogdan** [comment]
Yes, there is an interest. I don't know why we don't have it yet.

I would vote for some generic comment and make it not customisable. I am not sure why we need the config option. Can't imagine a use case when autogenerated comment is not enough.

I would propose something like this:

``` js
/* File generated by js-routes #{gem version} 
 * based on rails routes of #{Rails.application.class.to_s}} 
 */
```

Do you think there is any other information needed?
I though it would be cool to include the commit hash, but I don't know a unified easy way of doing it.

**Comment by jordanstephens** [comment]
Okay, this sounds good to me!

I'm not sure about including the commit hash, but I'll throw together a pull-request with your proposal.

**Comment by le0pard** [comment]
@jordanstephens I think version of gem good for beginning
