### ISSUE TITLE
Option to remove :format

### ISSUE THREAD

**Issue by gitChang** [railsware/js-routes#156]
First of all, I would like to say thank you, for bringing restful routes to asset pipeline. 

I'd just like to suggest an option to remove `(.:format)` from the string representation of a path. Currently, my $resource factory (angularjs), in order to get the `/api/students/:id` string, I have to remove the `:format` parameter. 

Though, I could achieve this by making a filter, but it would be better if it is configurable.

Thanks.

**Comment by le0pard** [comment]
I expected, what if you remove `:format` from rails routes, in this case it also not show on JS side. Does this not works?

**Comment by gitChang** [comment]
I can't find any clean solution how to remove it (:format). But still, I'd rather do it on the client-side routing. 

For the meantime, string manipulation is enough.

**Comment by le0pard** [comment]
I added in previous comment how to remove it :)

**Comment by gitChang** [comment]
:+1:  :D ... but in `scope 'foo', defaults: { format: false } do ... end` the `:format` is still there. Any ideas? 

Thanks Man...

**Comment by le0pard** [comment]
Add this to `resources` inside scope, not for `scope` itself

**Comment by gitChang** [comment]
I think that's the best way for now. Would you consider adding the option in the next version?

**Comment by le0pard** [comment]
I think it is question for @bogdan :)

**Comment by gitChang** [comment]
:D haha!  So, do I have to close this issue right now?

**Comment by le0pard** [comment]
As you wish.

**Comment by gitChang** [comment]
ok...thanks.
