### ISSUE TITLE
Make `default_url_options.host` optional for *_url helpers

### ISSUE THREAD

**Issue by ianlotinsky** [railsware/js-routes#157]
Problem: We have a multi-tenant app, where each customer has its own subdomain. We need `*_url` helpers to generate full URLs in various places. `default_url_options.host` only allows us to set one host, which will not work with subdomains.

Thoughts on making `host` optional and calculating `*_url` helper strings on the JavaScript side based on `default_url_options` and `*_path` helpers instead of entirely in Ruby?

**Comment by bogdan** [comment]
I think this is reasonable use case. I will gladly accept a PR.

**Comment by andrewhavens** [comment]
When I originally implemented this, my plan was to use `window.location` to determine the host and port. However, at the time, my PR was not merged because this library supports server-side JavaScript where `window` is not available. I'm not sure how to support this scenario for server-side JavaScript. Once we determine how to do that, the implementation is pretty easy.

**Comment by bogdan** [comment]
@andrewhavens taking host/port from `window.location` is not what @ianlotinsky wants as I understand. But anyway, I don't know why we can not check the `window.location` presence and take host port from there if it is available. @le0pard ?

**Comment by le0pard** [comment]
Yes, if we need use `window.location`, we just need to check, what this object available in JS environment. Only question - how this feature will works without `window.location`? But I just thinking - if you need so custom URL helpers, so why just not write simple helper function? Example:

```js
var generateCustomUrl = function(hostname, path){
  return '://' + hostname + path;
}
```

Where `hostname` - any stuff, `path` - result of any route method.

Most simple way to do this like we trying to do with serializer -  allow to provide host as function, our code will call it, but catch any exception, if developer make error in it :)

**Comment by bogdan** [comment]
I was thinking that if host/port were not specified at ruby level and there is no `window.location` (or even if it is), you can still specify those options at JS level on per page basis: `Routes.default_url_options.host = 'customer.site.com'`

**Comment by andrewhavens** [comment]
I agree.

I should be able to submit a PR for this by Tuesday.

**Comment by ianlotinsky** [comment]
Thanks, @andrewhavens!

FWIW, `window.location` was precisely what I had in mind, so +1.

**Comment by ianlotinsky-lz** [comment]
@andrewhavens is this something you are still planning to implement?

**Comment by ianlotinsky** [comment]
@andrewhavens, is this still something you are planning to implement?

**Comment by andrewhavens** [comment]
Hi @ianlotinsky sorry I've been really busy these last few weeks and haven't had a chance to implement this. Still planning to get to it (hopefully this week).

**Comment by jessicard** [comment]
:+1: I would also like `default_url_options.host` optional, or at least dynamic, so that it can be set for different environments.
