### ISSUE TITLE
Does it still work with Heroku?

### ISSUE THREAD

**Issue by viniciusoyama** [railsware/js-routes#165]
Hi! I'm wondering if this gem still works with Heroku, since labs use-env-precompile is not available anymore.

I've created a new file like app/assets/javascripts/routes.js.erb with the following content:

```ruby
<%= JsRoutes.generate() %>
```

And required this file on my main js file. But it just generates the boilerplate Route's functions and doesn't initialize any route for the js code. For now I'm just using it directly on the layout but I don't think that is the best solution. 

Thanks!

**Comment by bogdan** [comment]
Using it in the layout will extend your pages size. That can only be fine in one-page heavy JS apps.
Otherwise it is not so good option.

Can you generate a file inside rails initializer like: `JsRoutes.generate!(Rails.root.join("/app/assets/javascripts/routes.js"))`? It still will require you to relaunch your web server to regenerate routes file. But I feel it is a little better. 

I've never used Heroku myself so I am not a good adviser here. Maybe others will help.

**Comment by viniciusoyama** [comment]
Hi! Thanks for the quick feedback.

I agree with you that it isn't the best solution. I'm also using cloudfront to serve the assets so I really need the routes to be precompiled by the pipeline. Putting all those routes on the html increases the page size.

I'm thinking that, for now, the solution is to create a rake task to run after each deploy (when all environment on heroku is OK). This task will execute ```JsRoutes.generate ``` and copy the javascripts/routes.js to public/assets/javascripts/routes-DIGEST.js.
De digest can be a md5 o the file and after that I must manually update the manifest.yml to know that.
With this I can include the file with the javascript_tag helper on my layout and the js file can also be cached and served using cloudfront due the digest.

What do you guys think?

**Comment by viniciusoyama** [comment]
Another idea is to create a helper method
js_routes_javascript_tag() that will evaluate to a script tag pointing to something like
/assets/javascript/js-routes-DIGEST.js
The digest can be generated during the precompile step based on the routes.rb file and saved on publig/js_routes_manifest.yml or something like that.

Then we create a rack middleware to intercept all calls for /assets/javascript/js-routes-*.js and generate the file saving it on public/assets/javascript. Next time this rack will not be used because the generated file will be served by ActionDispatch::Static.

I'm just coming up with ideas because I can't figure out how to do to this gem work properly on Heroku. LOL
