### ISSUE TITLE
Not exposing any routes to an attacker, but still accessible by javascript

### ISSUE THREAD

**Issue by mikebaldry** [railsware/js-routes#166]
It'd be cool to store the routes with the key being hashed, then the value being encrypted with the original key. This way nothing would be gained by looking at the routes, only when you made use of a route would it expose it (and if you're using an admin_deploy_nukes_path, you'll have probably authenticated them already)

example:

```
routeMap = {
 "<sha1 of admin_deploy_nukes_path>": "<AES encrypted path, with the key admin_deploy_nukes_path>"
}

findRoute = (routeName) ->
  hashedRouteName = SHA1(routeName)
  AES.decrypt(routeMap[hashedRouteName], routeName) #assuming (data, key)
```

Of course this would require 2 extra libraries but I guess they're pretty small and the amount of data being encrypted/hashed would be small, so pretty quick. 

Maybe overkill but might be a nice option?

**Comment by le0pard** [comment]
You can remove unneeded routes by config, if it is so scary to show it is in JS.

**Comment by bogdan** [comment]
That looks interesting as an idea. I don't see a way of implementing that without changing an API as you call a route like this:

``` js
Routes.user_path(1)
// but not like
Routes.run(:user_path, 1)
```

This is kind a big deal and I don't think that a lot of people will want it even if they are seriously security-concerned.

It could be done in ruby without changing an API with method missing that is not available on JS.
Let's think of a way to do it without API change or other concerns.

**Comment by kriansa** [comment]
I don't think it'd add any security to your app at all, since your routes would still be exposed anyway. Not only that, but decrypting this file wouldn't be difficult at all, since your legitimate client already do so:

```js
findRoute('admin_deploy_nukes_path')
```

Honestly, I don't see any benefits on it.

**Comment by thomasbiddle** [comment]
While interesting; security by obfuscation isn't security.

**Comment by mzedeler** [comment]
This issue seems to be ready to be closed...?

**Comment by bogdan** [comment]
It kinda waits for anyone smarter to make a proposal how to solve it.

**Comment by bogdan** [comment]
As ESM tree shaking with Webpacker is now supported in v2.0. I recommend that setup. Please see https://github.com/railsware/js-routes#what-about-security for more info.
