### ISSUE TITLE
Ability to specify anchor in path

### ISSUE THREAD

**Issue by jessicard** [railsware/js-routes#167]
I'm sorry if this is already supported or isn't in the js-routes wheelhouse, but I wasn't able to find it in the documentation. I'd really like to be able to specify an anchor to hit with a route.

**Comment by le0pard** [comment]
```js
var urlWithAnchor = Routes.someRoutePath({anchor: 'someCoolAnchor'});
// or
var urlWithAnchor = Routes.someRoutePath() + "#someCoolAnchor";
```

**Comment by jessicard** [comment]
Wonderful, thanks! :)

**Comment by bogdan** [comment]
Need to update Readme with anchor example
