### ISSUE TITLE
tmp:cache:clear requirement slows down deployments

### ISSUE THREAD

**Issue by steakchaser** [railsware/js-routes#168]
Thanks for the nice gem, but having to call `tmp:cache:clear` is really slowing down asset compilation (local or server).  I realize the gem uses `Rails.application.routes` to inspect the routes, but is there any other way to do this?  Any ideas on how to speed things up?

**Comment by bogdan** [comment]
How did you end up having it in your deployment?
You only need `tmp:cache:clear` when you made changes in js-routes configuration and you only need it in development. In production it wasn't ever an issue.

**Comment by steakchaser** [comment]
We precompile assets on the server using the standard Capistrano 3 tasks, so in our case we have to clear the cache on the server.  

To work around it, we changed to a local precompile.

**Comment by le0pard** [comment]
By default capistrano use `rake assets:precompile`, which recompile only changed files. So in this case no need to cleanup cache for each deploy.

**Comment by bogdan** [comment]
I am thinking about this line of code:

https://github.com/railsware/js-routes/blob/master/lib/js_routes/engine.rb#L17

``` ruby
      routes = Rails.root.join('config', 'routes.rb').to_s
     ...
      Rails.application.assets.depend_on Rack::Utils.escape("file-digest://#{routes}")
```

We can have the same for `config/initializers/jsroutes.rb`. If I got it correctly, it will help sprockets to know that routes.js should be recompiled on changes at this initialisation file.

**Comment by steakchaser** [comment]
@bogdan are you suggesting that the above would tell sprockets to re-compile js-routes if the actual `routes.rb` file has changed?  Sounds like a good idea :+1:

**Comment by bogdan** [comment]
@steakchaser it should already be working like that. Do you have any issues with that?

**Comment by steakchaser** [comment]
We've always had to run `tmp:cache:clear` even when `routes.rb` changes.  I'll test it out again tomorrow to confirm.

**Comment by steakchaser** [comment]
Hi @bogdan, confirmed that any time we change `routes.rb` we have to run `tmp:cache:clear` prior to compiling assets, otherwise the changes do NOT get picked up.  Thanks for looking into this!

**Comment by le0pard** [comment]
@steakchaser we need also rails version to check and reproduce this on our side :)

**Comment by le0pard** [comment]
@steakchaser should be fixed by using sprockets-rails < 3
