### ISSUE TITLE
Default serializer turns spaces into +

### ISSUE THREAD

**Issue by jessicard** [railsware/js-routes#169]
I'm using js-routes to create some routes in my application with params. It looks like when I give an object to params that contains a value that has spaces, the spaces come through as "+". I wasn't expecting this to happen. Is this the default behavior? Should it be?

**Comment by le0pard** [comment]
Hello. Yes, it default behavior for HTTP resources: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent You can check, what rails server should handle "+" as space without problem

**Comment by jessicard** [comment]
Ah, gotcha. Thanks for clarifying. It would be awesome if this could be linked to in the documentation for the default serializer!

**Comment by le0pard** [comment]
@jessicard because js-routes should be first of all be like Rails routes helper, default serializer trying to work like in Rails:

```
2.2.3 :001 > app.inboxes_path({test: "Some text"})
 => "/inboxes?test=Some+text"
```
