### ISSUE TITLE
Add Rails 5.0 compatibility

### ISSUE THREAD

**Issue by dlupu** [railsware/js-routes#171]
Hello, 

I'm migrating a project from Rails 4.2.5 to Rails 5.0.0.beta1 and I'm getting the following error

ActionView::Template::Error: private method `routes' called for #<ActionDispatch::Routing::RouteSet::NamedRouteCollection:0x007fde7a5e4498>

Complete backtrace : https://gist.github.com/dlupu/8d122a4d8ff64ab5cc4f

BR
Dorian

**Comment by le0pard** [comment]
I will review PR if any. Right now I don't have project with rails 5 to check this problem :)

**Comment by nadavb** [comment]
For some reason someone made the routes private in NamedRouteCollection  in Rails 5. In Rails 4 it was accessible.

How do we access the routes now?

**Comment by le0pard** [comment]
@nadavb I have project with rails 5.1.5 - js-routes (1.4.3) works without problem. So check you project.
