### ISSUE TITLE
Can't upgrade to 1.2.0 from 1.1.2 - default url options inserted when not accepted

### ISSUE THREAD

**Issue by rosenfeld** [railsware/js-routes#173]
```ruby
post 'action', format: false, as: :action
JsRoutes.setup {|c| c.default_url_options = { format: :json } }
```

Routes.action_path() generates '/action' up to 1.1.2 but will generate '/action?format=json' in 1.2.0.

**Comment by le0pard** [comment]
Hm, looks like rails app:

```ruby
post 'action' => 'users#users', format: false, as: :action

2.3.0 :001 > app.action_path()
 => "/action"
2.3.0 :002 > app.action_path(format: :json)
 => "/action?format=json"
```

**Comment by bogdan** [comment]
Why do you specify `format: false` here? You will not have any route that would support format. So `/action.json` would result in 404 for you. I think this is misconfiguration.

**Comment by rosenfeld** [comment]
No, this is not a misconfiguration, and I actually want the app to return 404 if /action.json is requested. The actual routes look like this in my app:

```ruby
scope format: false, constraints: {id: /\d+/} do
  # non JSON routes go here
end

scope format: true, constraints: {format: /json/, id: /\d+/} do
  # JSON routes go here
end
```

**Comment by bogdan** [comment]
Sorry, I got you wrong. You are right. I am thinking about the issue now to see what we can do.

**Comment by rosenfeld** [comment]
There are some reasons, but I never use responds_to. It's an SPA and most actions will either return no content (just a status) or JSON. The main reason why I care about the format is caching. Rails is not very smart with regards to caching because it only stores the content, not the headers, like content-type. So, if some user requests '/action' and it returns content-type: 'application/json', next time, it will return content-type: 'plain/text' when rendering a 304. But it relies on the format to generate the content-type in those cases, so it would return 'application/json' if '/action.json' is used instead, that's why I force it to be specified in the first place.

**Comment by bogdan** [comment]
It seems `default_url_options` has the same behaviour as JS routes now:

``` ruby
resources :sites, format: false
UrlGenerator.default_url_options.merge!(format: 'json')

UrlGenerator.sites_path # => "/sites?format=json"
UrlGenerator.sites_path(format: nil) # => "/sites"
```

The behaviour of js-routes is now consistent with rails.
The last line seems like a not so pretty solution for you - you will need to update a lot of places.

Is there a way we can recreate the Url Generator with behaviour you need on Backend?

**Comment by rosenfeld** [comment]
Would it be hard to support some new option like default_format and use it only when format is not false?

**Comment by bogdan** [comment]
No, I even though about more general `default_optional_parts`, but want to see if there are rails analogies for that first. Is there any suggestion how to reach your behaviour on backend?

**Comment by rosenfeld** [comment]
I don't think it's possible, specially because this is the only way to tell Rails to accept a "format" regular parameter without letting him make any assumptions about the request format. But, from the client-side point of view, it's really frustrating to have to specify the format when a single format is accepted. Unfortunately the Rails routes API only allow the format to be specified through a regular expression, which makes it impossible to handle such case in a transparent way from js-routes. That's why I think the proper way to handle this case is to add a js-routes specific configuration to tell it which format should be the default one when a format is allowed (it's not false). I think the format is special enough to deserve its own configuration...

**Comment by bogdan** [comment]
You can do `*_path(params: {format: 'json'})` to produce `.json` route to any route with any definition in rails. Same can be possible with js-routes. 

I would disagree on special status of `format`: `(/locale/:locale)` can have the same idea if some routes support it and some don't.

**Comment by rosenfeld** [comment]
Those cases are different because locale, differently from format, have no special meaning in Rails. While it's possible to specify format: false when defining a route, there's no "locale: false" or something like that. Anyway, I can understand your point of view, implementation-wise to attempt to handle other more general cases. I guess you want to specify default values for optional params when they exist and use that for handling the format case, but I still think those features should be handled differently from each other.

**Comment by bogdan** [comment]
`:format` is special only at the controller level, but not router level. Here is example of locale used in the same way:

```
scope "/locale/:locale" do
  resources :sites
end

resources :images
```

In this case you might want to set `locale: current_user.preferred_locale` as parameter for `site_path` but not for `image_path`.

**Comment by rosenfeld** [comment]
There is a difference here. Rails itself knows about `format`, but it doesn't care about `locale`. Only your application itself is aware of the special meaning of `locale`. But Rails will decide on which content-type to serve for cached responses based on the `format` parameter. It will also interpret 'any/route.format' automatically. In that sense `format` is very special. Also, since the `format` is required in some routes and should not be informed in other, it's also an special parameter in the routes specification. Failing to inform the format will yield to a 404 when it's required, for example. This is different from regular optional route params. If `locale` is an optional parameter and it's not specified the server-side code will take care of setting the default parameter. I can't do that with format as the controller won't even be called and Rails will serve a 404 response instead.

Ideally, I'd prefer to specify the default format as 'json' for all routes returning a JSON directly in the routes definition, for example:

```ruby
scope format: true, constraints: {format: /json/, id: /\d+/}, defaults: {format: 'json'} do
  post 'some/action' => 'some#action'
end
```

Then, if the user does not specify '/some/action.json' but '/some/action' instead the framework would assume the format is 'json' for caching purposes. But I don't think this is currently a possibility with the routes DSL. As a work-around I'd be happy to provide a default format in the client-side integration (where the route name is actually used) whenever a format is allowed (it's not false).

**Comment by bogdan** [comment]
When you say "`Rails` knows ..." it is too large scope. We only care about smaller part: routes generation that doesn't have a format special status: route generation doesn't care about content-type, response caching. It doesn't even care about controllers because they are only related to dispatch, but not to URL formatting. If you would grep js-routes source code or route formatter code in rails, you wouldn't find any mentions of `format`.


I think `default_route_parts` would work fine for you: it will insert a parameter to an URL generator only if it is a route parameter but never as an query string parameter. This option will not even have to do anything with required or optional parameters.... it will just care if they are part of current route or not. 
Better name for parameter is welcome.

**Comment by rosenfeld** [comment]
I think even the router knows about the format. For example, if you write this:

```ruby
get 'some/action' => 'some#action'
```

Then it will accept `/some/action.json`, `/some/action.xyz` and so on. This behavior is not specified in the route and it doesn't happen for locale or any other parameter, so it must be a special parameter. If you grep for format inside `actionpack/lib/action_dispatch` you'll find a lot of code related to `format`:

`grep -RIw format actionpack/lib/action_dispatch`

Anyway, I don't really care about whether it's special or not if I'm able to reach my goals. `default_route_parts` sounds like a good name to me. But I'm not aware of the router internals so I'm not sure if you can get the right information from the routes to understand that format is part of some routes and not of others... If it works for the use case I mentioned in the beginning of this thread, then it will be perfect. Thanks.

**Comment by bogdan** [comment]
You didn't hear me: I said `format` IS related to dispatch but IS NOT related for formatting (that is part of `action_dispatch` directory - because it basically includes everything - but not part of URL dispatch process). 

I'll work on this new option some time this week. Stay tuned.

**Comment by rosenfeld** [comment]
Great! Have an awesome New Year! :)

**Comment by rosenfeld** [comment]
Nevermind, this new option is not really required for my use case as I could figure out how to specify the default format directly in the routes definition:

```ruby
scope format: true, constraints: {format: 'json', id: /\d+/}, defaults: {format: 'json'} do
  # JSON routes go here
end
```

Feel free to reopen if you are still interested in the feature for other purposes.

Thanks!

**Comment by bogdan** [comment]
I would not do it then: if it is not yet present in rails - I don't think it makes sense.

**Comment by rosenfeld** [comment]
Sorry, I was too fast. app.some_route_path will work with the route above but js-routes will complain about format missing in this case. When I first tested it worked but maybe it was due to some old tmp. After `rake tmp:clear` it was back to complaining about the missing `format` parameter... Do you think you can get js-routes to work like Rails path helpers?

**Comment by bogdan** [comment]
Can you show me your current configuration and route you get at rails and do not get in js-routes?

**Comment by rosenfeld** [comment]
Sure: https://github.com/rosenfeld/jsroutessample

**Comment by bogdan** [comment]
Fixed in master. I would appreciate if you could try to use it from there before I release.

**Comment by rosenfeld** [comment]
I can't check master due to this commit, which makes it incompatible with sprockets-rails 3.0.0: https://github.com/railsware/js-routes/commit/8fc4414cc9b044a0b4061dacc1e8a4bf3a4f635d

**Comment by rosenfeld** [comment]
I removed the '< 3.0.0' constraint in my fork, branch 'sprockets3' and it worked.

**Comment by bogdan** [comment]
@le0pard why did you add a limitation to gemfile? Is it actual now?

**Comment by le0pard** [comment]
@bogdan this gem is compatible with sprockets 3, but not with sprockets-rails 3. It is because `depend_on` stop working in rails engine and change routes.rb will not trigger to change js file.

**Comment by rosenfeld** [comment]
How about creating a custom Sprockets directive `depend_on_routes` and add it to the file with the routes?

**Comment by rosenfeld** [comment]
```ruby
class Sprockets::DirectiveProcessor
  def process_depend_on_routes_directive
    process_depend_on_directive 'config/routes.rb'
  end
end
```

**Comment by le0pard** [comment]
I thinking about this, but this can be not the best way for this and I am not sure, what this will work with routes.rb, which is not asset file.

**Comment by rosenfeld** [comment]
What part of the code specifically is not being called when routes.rb is changed?

**Comment by le0pard** [comment]
@rosenfeld this one - https://github.com/railsware/js-routes/blob/master/lib/js_routes/engine.rb#L15-L18

**Comment by rosenfeld** [comment]
I'm trying to understand this part:

`initializer 'js-routes.dependent_on_routes', after: "sprockets.environment" do`

Who's notifying about 'sprockets.environment'? I can't find any initializer with such name in sprockets or sprockets-rails sources...

**Comment by rosenfeld** [comment]
My idea would be to change `js-routes.js.erb` to prepend it with:

```eruby
<%= depend_on_routes %>
```

And add the directive as I showed before.

**Comment by le0pard** [comment]
@rosenfeld if this possible - please create PR. It will be better to see how it will looks like in code :)

**Comment by rosenfeld** [comment]
Ok, but I have left home already and should only be back at night. It's very likely I'll have to go to the dentist tomorrow morning :( And there are also a few things I must finish for work tomorrow, so it's more likely I would only be able to give it a try on Tuesday...

**Comment by le0pard** [comment]
@rosenfeld no problem. It is open source :)

**Comment by rosenfeld** [comment]
I'm closing this issue for now, since it has been resolved. I'll open a new one requesting sprockets-rails 3 support.

**Comment by rosenfeld** [comment]
By the way, thanks for the fix @bogdan!
