### ISSUE TITLE
Problem with singular form of routes

### ISSUE THREAD

**Issue by zeuge** [railsware/js-routes#174]
Hi.
I use this settings in routes.rb 
```
resources :budgies do
  get "descendents"
end
```

And I define the singular form of a resource in inflectors.rb (because by default it does instead of "budgy" "budgie"):
```
ActiveSupport::Inflector.inflections do |inflect|
  inflect.irregular "budgie", "budgies"
end
```
But I still see in Routes method "budgy_path", and I don't see method "descendents_budgie_path"

**Comment by bogdan** [comment]
Hm I didn't know that routes should support custom inflections. I'll add a support for those when get some time.

**Comment by bogdan** [comment]
@zeuge I've added a test for the case you explained. Everything works in the same way as rails:
https://github.com/railsware/js-routes/commit/b1040832d8b09579f227d10209137b2d2afd8c36

I don't see `descendents_budgie_path` neither in rails nor in js-routes. There is `budgie_descendents_path` for both instead.

**Comment by bogdan** [comment]
No follow up - closing. I wasn't able to find an issue.

**Comment by achru** [comment]
@bogdan the thing is that the generated path is generated with /budgie/ instead of /budgies/ and it gets 404 from rails side

**Comment by bogdan** [comment]
@achru can you reproduce it in the js-routes test suite?

**Comment by achru** [comment]
hey @bogdan - I was using 1.0.1 version where that happened - updated to current release and it's working, sorry for bothering mate :)
