### ISSUE TITLE
Please add support for sprockets-rails 3.0.0

### ISSUE THREAD

**Issue by rosenfeld** [railsware/js-routes#175]

**Comment by jaredbeck** [comment]
Background:

- js-routes 1.2.0 does not constrain the version of sprockets-rails.
- js-routes 1.2.1 adds a version constraint: `add_runtime_dependency(%q<sprockets-rails>, ["< 3"])`

The version constraint was added by https://github.com/railsware/js-routes/pull/170.  The reason given was:

> .. because sprokets-rails >= 3 broken some test cases. Right now I didn't found documentation how to use depend_on on version 3 ...

**Comment by jaredbeck** [comment]
For projects that need to use `sprockets-rails 3`, what are the consequences of staying on `js-routes 1.2.0`?  Thanks.
