### ISSUE TITLE
js-routes + heroku

### ISSUE THREAD

**Issue by tchret** [railsware/js-routes#180]
Hey guys,

I'm facing a strange issue.
I've ~ 20 routes included in my config and it works perfectly (both on local/heroku)

But it looks like I can't include more routes in production, when I try to incude an other route, it update well the `Routes` object on my localhost but not on Heroku.

**Comment by pathouse** [comment]
@tchret had the same issue and bumping the asset version fixed it

in config/environments/production.rb

```
  # Version of your assets, change this if you want to expire all your assets.
  config.assets.version = '1.0'
```

**Comment by cimm** [comment]
Same problem here, the file is not recompiled. Is this something that can be fixed, or do we now have to update the assets version each time we change anything in the js-routes config?

**Comment by pathouse** [comment]
@tchret @cimm updated solution for this:

define the routes.js.erb file as described in the README but add this line:
```
<%
