### ISSUE TITLE
How does :include work?

### ISSUE THREAD

**Issue by lesliev** [railsware/js-routes#182]
I don't understand how the include option is supposed to work, since the default is to include everything. I have been trying to include only specific routes like this:
```
JsRoutes.setup do |config|
  config.exclude = [/.*/]
  config.include = [/^admin_account_group/, /^admin_master_account_group/]
end
```

But that includes nothing. Is there any way to only include specific routes? A typical production app has a massive routes file and it would be a waste to have to download the whole thing if the JS is only using a few routes.

**Comment by le0pard** [comment]
remove in this case `exclude` rule, because you exclude everything.

**Comment by lesliev** [comment]
Aha, apologies, that works fine. I had not run `rake tmp:cache:clear`, so I was seeing the routes as they were before changing the configuration.
