### ISSUE TITLE
prefix setting not being applied

### ISSUE THREAD

**Issue by tknarr** [railsware/js-routes#186]
This seems related to, or maybe the same thing as, issue #104. I use the initializer from the README, and set config.prefix to Rails.application.config.relative_url_root. In development it works fine, the prefix shows up in the paths generated by the `*_path()` functions as expected. In production, the prefix doesn't appear. I tested it with a hard-coded string and got identical results. I'm not using Heroku or anything, it's a vanilla setup: Apache and Passenger for the server, deploying via RubyMine's built-in SFTP tool (confirmed that the results are what I expected) and using the latest version of js-routes (1.2.5) with Ruby 2.2.4 and Rails 4.2.6. I made sure to stop Apache and run the `tmp:clear` and `assets:clobber` Rake tasks before doing the `assets:precompile` step, all with RAILS_ENV=production set. The initializers are running during the precompile, I can see the output and a `puts` statement in my initializer shows js-route's config.prefix set to the expected string "/CertificateAuthority" for the sub-URI I have the application installed in.

I'm going to dig down into the code to see if I can figure out where the prefix is going missing and why it only affects production and not development.

**Comment by le0pard** [comment]
I think problem in caching of assets. If you change initializer values, it will not change content of js files and sha1 checksum for this files will be the same. That is why it will be not recompile.

**Comment by tknarr** [comment]
I thought about that, that's why I did the `tmp:clear` and `assets:clobber` tasks to clear out all the precompiled assets and the cache before I did the precompilation. It's got to be something to do with precompilation, I've checked backwards and forwards and that's the only difference between the two environments I can find, but I don't know exactly what. Yet. With luck it'll turn out to be something I didn't realize I fumbled.

**Comment by le0pard** [comment]
You can also try to use erb with ruby generator:
```
# app/assets/javascripts/routes.js.erb
<%= JsRoutes.generate(prefix: "/CertificateAuthority") %>
```

**Comment by tknarr** [comment]
It looks like I did fumble something. I did a from-scratch deployment making sure to double-check each step and now ff I hardcode the string in the initializer I can make it work in production. It's when it's trying to get it from Rails.application.config.relative_url_root that it's failing. So it's not a js-routes bug (but maybe something to put in the README), and since bundler and rake don't have access to the Passenger configuration I may just have to pass the correct value via an environment variable during precompilation (RAILS_RELATIVE_URL_ROOT works but it also messes up precompilation of application.scss). Maybe tracking down how it makes this work for URLs in .css assets will give me a clue to a more reliable method.

**Comment by tknarr** [comment]
OK, now that my brain's fully on track again. It looks like relative URL root during precompilation's a problem inside the Rails asset pipeline itself. You either have to set js-route's config.prefix to the correct literal string in the initializer, or set the RAILS_RELATIVE_URL_ROOT environment variable correctly when doing the assets:precompile task. I tried your ERB fix and it worked only under the same conditions the initializer works: set to a literal string or RAILS_RELATIVE_URL_ROOT set correctly during precompilation.

This is also required for fixing the paths in .css assets when installed in a sub-URI too, it's not just js-routes affected. I'm going to close this issue and submit a pull request with an addition to the README.
