### ISSUE TITLE
Js-Routes along with Route-Translator Gem

### ISSUE THREAD

**Issue by tommyalvarez** [railsware/js-routes#190]
Hi,

The route translator gem: https://github.com/enriclluelles/route_translator produces as an example output the following routes: 

categories_items_en GET      /products/categories(/*x)(.:format)                     items#index {:locale=>"en"}
categories_items_es_ar GET      /productos/categorias(/*x)(.:format)                    items#index {:locale=>"es-AR"}                      
item_js_update_show_en GET      /products/:item_id/js_update_show(.:format)             items#js_update_show {:locale=>"en"}
item_js_update_show_es_ar GET      /productos/:item_id/js_update_show(.:format)            items#js_update_show {:locale=>"es-AR"}
items_en GET      /products(.:format)                                     items#index {:locale=>"en"}
items_es_ar GET      /productos(.:format)                                    items#index {:locale=>"es-AR"}
item_en GET      /products/:id(.:format)                                 items#show {:locale=>"en"}
item_es_ar GET      /productos/:id(.:format)                                items#show {:locale=>"es-AR"}
categorized_item_en GET      /products/:category_slug/:id(.:format)                  items#show {:locale=>"en"}
categorized_item_es_ar GET      /productos/:category_slug/:id(.:format)                 items#show {:locale=>"es-AR"}

For this routes, js-routes generates them as: "/productos/1?locale=es-AR"
I would like js-routes to ignore the url parameter ?locale=es-AR totally. Is that possible in any way?

**Comment by bogdan** [comment]
Yes, it is possible by introducing a custom serializer:

``` ruby
JsRoutes.configure do |c|
  c.serializer = <<JS
function(object, prefix = null) {
  if (object && object.locale) {
    delete object.locale;
  end
  return Routes.serializer(object, prefix);
}
JS
```
