### ISSUE TITLE
Issue with engines that don't have specified :as option when mounted

### ISSUE THREAD

**Issue by bogdanRada** [railsware/js-routes#195]
As per discussion here: https://github.com/railsware/js-routes/issues/194 , there is an issue when using engines like this:

```
mount MyGem::Engine => "/products"
```
without specifying an **:as** option to manually name this route, the routes inside the gem are not being collected and they are missing from generated source. 

I think issue is at this line https://github.com/railsware/js-routes/blob/master/lib/js_routes.rb#L153

because only the named routes get collected by this code:
```
 Rails.application.routes.named_routes.to_a
```
Would be really nice if we could collect the other routes also.  The code for generating the routes in the JS file i don't think that needs any modification

Thank you very much for the help.

**Comment by bogdan** [comment]
It seems that in case of anonymous mount the only URL helper available is the root:  `Rails.application.routes.ulr_helpers.my_gem_engine_path` in your case.... I fixed that in current master. Can you check it locally?

**Comment by bogdanRada** [comment]
i am not at my house right now, I will check tomorrow. Thanks a lot .

**Comment by bogdanRada** [comment]
I checked but is not working as i am expecting. It only works if i do this:
```ruby
JsRoutes.setup do |config|
  config.include = [ /^my_gem/]
end
```

But if if i do this:
```ruby
JsRoutes.setup do |config|
  config.include = [ /^products/]
end
```

I don't see any routes from that engine in the generated source. 

Or maybe this is expected?

**Comment by bogdan** [comment]
Give me your configuration of main app routes and mounted app routes and the output of `rake routes`

**Comment by bogdanRada** [comment]
I use this In Rails routes:
```ruby
MyGem::Engine.routes.draw do
  resources :bags, as: 'product', except: [:destroy] do |product = 'bags'|
    member do
       get 'confirm-action/:type' ,:as => :confirm_action, :action => :confirm_action
    end
  end 
end
```

And then i mount it like this:
```ruby
Rails.application.routes.draw do
    mount MyGem::Engine       => '/products'
end
```

The engines routes look like this:
```bash
Routes for MyGem::Engine:
confirm_action_product GET   /bags/:id/confirm-action/:type(.:format) my_gem/bags#confirm_action
         product_index GET   /bags(.:format)                          my_gem/bags#index
                       POST  /bags(.:format)                          my_gem/bags#create
           new_product GET   /bags/new(.:format)                      my_gem/bags#new
          edit_product GET   /bags/:id/edit(.:format)                 my_gem/bags#edit
               product GET   /bags/:id(.:format)                      my_gem/bags#show
                       PATCH /bags/:id(.:format)                      my_gem/bags#update
                       PUT   /bags/:id(.:format)                      my_gem/bags#update

```

And main application has this:

```bash
                  Prefix Verb     URI Pattern        Controller#Action
                  core             /                  Core::Engine
                  my_gem          /products             MyGem::Engine
```

**Comment by bogdan** [comment]
I am able to access your mounted app routes in test suite:

https://gist.github.com/a097ef3d7df06c0045cc6ed335627805

**Comment by bogdanRada** [comment]
Yeah but You actually named your engine Products . Try with some other random name . 

But i think its ok. At least now works if the regex used is the engine name. So i am ok with this. Thank You very much. 

I am ok with this workaround.

**Comment by bogdan** [comment]
I didn't get the difference between my configuration and yours. I didn't name it more than you did.

**Comment by bogdanRada** [comment]
It's perfect. It least now i can generate those routes. But my impression was that when i configure the gem and specify those regular expressions , each regular expressions should be about what URL prefixes i need. 

So for my gem all routes în browser are accesible via /products  prefix so i was expecting to use that în the regular expressions but i think i might have misunderstood how those expressions are used. 

So its ok. At least i know now how to use those expressions and it works if i put the engine name în that regular expression. Thank You very much

**Comment by bogdan** [comment]
Ok, I see... yes this is another issue....

**Comment by bogdanRada** [comment]
i think this can be closed. Not sure about the other issue if you want me to open a new issue or maybe there are already plans to handle that.
