### ISSUE TITLE
Possible to rewrite the generated paths?

### ISSUE THREAD

**Issue by Frexuz** [railsware/js-routes#200]
Hi. I'm using the route_translator' gem.

This generates routes like so:

`calendar_path`
`calendar_br_path`
`calendar_en_path`
`calendar_fr_path`

And for some reason, the base route `calendar_path`, is not included in the generated list in `js-routes`, which is the route that I need to use.

I was thinking to only include the `_en` paths, and then somehow just remove the language prefix. But I can't seem to find a way.

(I'd be happy with a monkeypatch as well)

**Comment by Frexuz** [comment]
Current ugly workaround:

```


  def generate_route_name(name, suffix)
    route_name = name.join('_')
    route_name << "_#{ suffix }" if suffix
    route_name = @options[:camel_case] ? route_name.camelize(:lower) : route_name

    # Custom replacing away _en
    route_name.sub!('_en', '')
  end
```

and a js helper around any route:

```
  var route = function(url) {
    return url.replace(/^\/en/, '')
  }

 EC.route(EC.routes.faqs_path());
```

**Comment by bogdan** [comment]
What kind of configuration should I have in routes file to get the routes like you have?

**Comment by Frexuz** [comment]
this is what I have:

```
gem 'route_translator'
```

initializer:

```
RouteTranslator.config do |config|
  config.generate_unnamed_unlocalized_routes = true
end
```

then wrap all the routes that you want translated in `routes.rb` with:

```
App.routes.draw do
  localized do
    resources :users
    resources :posts
  end
end
```

**Comment by bogdan** [comment]
It seems like RouteTransator make those unnamed unlocalized routes in a hacky way.
They are not listed in `rake routes`, therefore js-routes will not list have them too.

I think this is a route_translator issue that could have done better.

**Comment by Frexuz** [comment]
Hm, this is what i get with `rake routes`

```
search_br GET  /br/search(.:format)  shows#search {:locale=>"br"}
search_de GET  /de/search(.:format)  shows#search {:locale=>"de"}
search_es GET  /es/search(.:format)  shows#search {:locale=>"es"}
search_fr GET  /fr/search(.:format)  shows#search {:locale=>"fr"}
search_it GET  /it/search(.:format)  shows#search {:locale=>"it"}
search_pl GET  /pl/search(.:format)  shows#search {:locale=>"pl"}
search_pt GET  /pt/search(.:format)  shows#search {:locale=>"pt"}
search_tr GET  /tr/search(.:format)  shows#search {:locale=>"tr"}
search_en GET  /en/search(.:format)  shows#search {:locale=>"en"}
          GET  /search(.:format)     shows#search
```

**Comment by bogdan** [comment]
See the first column: there is no `search` record there. That means that `search_path` and `search_url` is not recognised as existing route.

**Comment by Frexuz** [comment]
Oh I see what you mean. Too bad :( I have to live with my hack i guess

**Comment by bogdan** [comment]
No, just go to the route_translator gem and ask for support there

**Comment by Frexuz** [comment]
Ye I will do that too :)
