### ISSUE TITLE
routes.js not created on vanilla gem install

### ISSUE THREAD

**Issue by XXChester** [railsware/js-routes#204]
Hello, 

I have included your gem, ran bundle install, added the require statement to my application.js and I ran " rake tmp:cache:clear" yet I still do not have a routes.js file. What am I missing? Is there a step I missed for generating the first time? I also tried using a bare bones config file but ti did not seem to change anything.

My environment is linux zorin, ruby 2.2.4, rails 4.2.6.

I am sure I am missing something as I am new to this. Any ideas?

**Comment by bogdan** [comment]
With rails asset pipeline you don't need `routes.js` file anymore. The installation with `routes.js` file is considered advanced and not default.

**Comment by XXChester** [comment]
Bingo. I guess I should've tried the "Usage" instructions but I assumed it wasn't configured so it wouldn't work.

Maybe we should add a small snippet to the documentation about not needing the file for vanilla rails?
