### ISSUE TITLE
Unclear Route validation message: amount of required parameters

### ISSUE THREAD

**Issue by iurevych** [railsware/js-routes#207]
Here is an example:
``` js
Routes.new_coupons_site_coupon_list_path(Site.id);
```

JS Routes throws an exception that the `id` is a required argument:
![campaign rules invite full screen image talkable 2016-08-17 14-15-53](https://cloud.githubusercontent.com/assets/325422/17734610/fcf195d6-6485-11e6-9762-ec2c805cd8ea.png)

In fact it asks me to pass a second argument, which is unclear from the exception message. Here is a working example:
``` js
Routes.new_coupons_site_coupon_list_path(Site.id, Campaign.id);
```

Ideally the exception `message` should be:
```
Route parameters passed: 1 out of 2 required. Route parameter missing: id.
```

Thanks.

**Comment by le0pard** [comment]
Problem with JS (of it is feature), that it does not strict about number of arguments in function

![unclear route validation message amount of required parameters issue 207 railsware js-routes 2016-08-17 14-30-28](https://cloud.githubusercontent.com/assets/98444/17734822/50796570-6487-11e6-9749-f01d283767d6.png)

**Comment by iurevych** [comment]
Hey @le0pard I'm not sure I follow your explanation. How about validating `arguments.length` first?

I can see the following source:
``` js
new_coupons_site_coupon_list_path: Utils.route(["site_id","id"]
```

Inside `Utils.route()` method you can easily check for `length` of this array and validate for an amount of required params first?

I may be wrong in my assumptions, this is just an idea.
Thanks!

**Comment by bogdan** [comment]
@iurevych route arguments can be passed in a different way:

```
new_coupons_site_coupon_list_path(1,2)
new_coupons_site_coupon_list_path({site_id, 1, id: 2})
# or even more idiotistic:
new_coupons_site_coupon_list_path(1, {id: 2})
```

As all of them are supported by rails, we should support them too. It makes it impossible to generate a good error message. Rails does its best to do so and we only clone the behaviour in JS routes.

**Comment by iurevych** [comment]
Got it, makes sense then.
