### ISSUE TITLE
Getting error rarely when calling a route method

### ISSUE THREAD

**Issue by PikachuEXE** [railsware/js-routes#208]
The error happens at
https://github.com/railsware/js-routes/blob/502692b471bde74d046203bf697c815008041d35/lib/routes.js.coffee#L92

Error message:
```
undefined is not an object (evaluating 'property.toString')
```

**Comment by le0pard** [comment]
Hello. Can you create test case or make test with this error?

**Comment by PikachuEXE** [comment]
I just raise this since I saw a JS error in our private JS error tracking
But I can't reproduce myself

Just want to know if it's easy to fix by just reading the code
If not let's close it until I can reproduce it with some sample code

**Comment by le0pard** [comment]
Need see what kind or route create this problem. Maybe in js-route method pass `null` instead params/ID?

**Comment by PikachuEXE** [comment]
The following code is called:
```coffee
some_id = $element.data("resource-id")

Routes.some_path({id: some_id})
```

And because of https://github.com/railsware/js-routes/blob/502692b471bde74d046203bf697c815008041d35/lib/routes.js.coffee#L86

The `id` is used without null check
I don't know if a null check should be put there though

**Comment by bogdan** [comment]
Yes, we can be more consistent there to rails:

```
>  site_path(Site.new)
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"sites", :id=>#<Site id: nil, name: nil, url: nil>} missing required keys: [:id]
from /Users/bogdan/.rvm/gems/ruby-2.3.0@talkable/gems/actionpack-4.2.6/lib/action_dispatch/journey/formatter.rb:46:in `generate'

**Comment by le0pard** [comment]
@PikachuEXE Fixed by https://github.com/railsware/js-routes/pull/209

**Comment by PikachuEXE** [comment]
Thx!
