### ISSUE TITLE
Sprockets 3 integration might not be working

### ISSUE THREAD

**Issue by PikachuEXE** [railsware/js-routes#211]
# Summary

When content of `config/routes.rb` updated
`Routes` in JS is not updated (e.g. no new function in `Routes` for new paths)
# Steps
- Run `rake assets:clobber tmp:cache:clear`
- Start server
- Visit any page with `js-routes`
- Ensure `Routes` present in JS
- Add a new path (even the controller is not there)
- Reload page
- Check `Routes` for function for the new path
# ENV
- js-routes (1.3.0)
- sprockets (3.7.0)
- sprockets-rails (2.3.3)
- rails (4.1.16)

I am unable to find the preprocessor in `Rails.application.assets.preprocessors`
And I think the change made in #202 does not use the new `JsRoutesSprocketsExtension` clas
For sprockets 2 & 3
That could be the reason of this bug

You might want to see [`i18n-js`'s implementation of multuple sprockets version support](https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/engine.rb)

**Comment by le0pard** [comment]
I think we good to accept PR (I not have time right now) :)

**Comment by PikachuEXE** [comment]
#212 is opened :)

**Comment by PikachuEXE** [comment]
Closing since #212 merged
