### ISSUE TITLE
Very Advanced Setup breaks dependence on the routes changes.

### ISSUE THREAD

**Issue by sponomarev** [railsware/js-routes#213]
Hi there,

We've noticed that routes dependence works for `js-routes` file only and doesn't work for advanced setup with a custom name for routes file. [Related code](https://github.com/railsware/js-routes/blob/master/lib/js_routes/engine.rb#L12). So, the assets won't be regenerated on any `config/routes.rb` changes.

It looks like it's the reason for #180. 

I have to proposals to resolve this issue:
- we can change documentation to include `<%= depend_on Rails.root.join('config/routes.rb') %>` explicitly in each custom file with `JsRoutes.generate`
- we can add yet another setup option where we have to include all custom files and then add `depend_on` for all of them in enging.

e.g.

``` ruby
# config/initializers/jsroutes.rb:
JsRoutes.setup do |config|
  config.files = ['admin/routes.js.erb', 'admin.js.coffee']
end
```

Any thoughts?

**Comment by bogdan** [comment]
@PikachuEXE is it related to your problem in #212 ?

**Comment by bogdan** [comment]
@sponomarev can we add a method into asset generation context like `= generate_js_routes(...)` that would unite the call of `depends_on` and `JsRoutes.generate` ?

If not, we can try `= JsRoutes.static_asset(self, options)` instead too.

**Comment by PikachuEXE** [comment]
@bogdan 
Yes
But #212 fixes basic setup (using default file)
Fixing this should be a separate thing

**Comment by sponomarev** [comment]
@bogdan Sounds good. I'll prepare a PR.

**Comment by bogdan** [comment]
Closing by inactivity.
