### ISSUE TITLE
Revisit default prefix setting (double prefix)

### ISSUE THREAD

**Issue by ekr1** [railsware/js-routes#221]
Hello,

the change from https://github.com/railsware/js-routes/pull/189 breaks existing applications, at least it has the potential to do so (and did break mine).

In my case, I got two prefixes in the URLs (i.e., a javascript helper "something_path" created the URL "/myapp/myapp/something" where "myapp" is the prefix).

As noted in that change, it is hard to create a test for it as it is hard to inject a prefix in the testing environment. In my case, I ran into the same trap - my application tests were fully green, and since I use javascript helpers only in a few places, the bug only surfaced after a few days in our integration/production environment. Debugging then also was "interesting", to say the least, and if not for our integration environments, it would have meant a relatively long downtime.

In my case, the solution was to disable the prefix altogether (from the point of view of js-routes) by creating an initializer:

    JsRoutes.setup do |config|
      # The prefix gets into the URLs from ... somewhere; avoid doubling it.
      config.prefix = ''
    end

As mentioned in the original change, it is hard to make this "right", and the rails routing prefix seems notorious for problems with several gems/asset generators, anyways. But a very noticeable change notice would be nice; even a notice during `bundle install` would be appropriate, I feel. I have no idea how easy/hard it is to add something like that, but it certainly would have spared me quite some time of debugging if I knew where to look.

Aside of that, thanks for this gem of a Gem. :)

PS: This issue is not about why I got double prefixes in the first place. The application it occured in started out in Rails 3, got migrated to Rails 4, and while the webserver in production is pretty simple (`thin` inside an Apache using the `balancer` reverse proxy module), it may well have some "specialty" in its setup (though I looked through everything and nothing seemed really out of place). This issue is strictly about informing people upon upgrade.

**Comment by le0pard** [comment]
@ekr1 you can read changelog before doing bundle update: https://github.com/railsware/js-routes/blob/master/CHANGELOG.md

**Comment by bogdan** [comment]
Are you running your app with `relative_url_root` in production but not in development, test or staging? If that is true, you are in trouble. 

I am not sure if the upgrade notice is worth it. Potentially every change can be breaking for an app. In this case, the break would have to be extremely visible if you would run your app on an env similar to production. If you did so, how did it pass through any very basic QA?

**Comment by ekr1** [comment]
@le0pard, the changelog contains "Use default prefix from  Rails.application.config.relative_url_root  #186" - sounds benign and trouble free at first glance, to me; more like some minor bugfix for some obscure issue which I do not need to concern me about (together with the fact that it's a minor bugfix release).

@bogdan, neither http://guides.rubyonrails.org/configuring.html nor https://apidock.com/rails/ActionController/AbstractRequest/relative_url_root contains any hint about the fact that one should expect problems when running it with or without in different environments.  It explicitely states that it *can* be used if the app is run in a "subdirectory" (in URL space).

We test with cucumber, capybara & poltergeist (=Chrome Headless), which manages the server part automatically for us, and do not need the prefix there. Everything worked fine with js-routes and any other gem before this change, from Rails 3 until 4.x.

Sure, every change can break an app, but *this* change has been in a minor release (1.2.5 => 1.2.6). I am assuming that this gem uses semantic versioning as usual, and that means that a minor (bugfix) release can *not* contain a breaking change (unless it truly is a bug). Since Gemfile allows syntax which automatically upgrades minor (bugfix) releases, there should be a clear warning. As the change is not backward compatible, it should have been a major release, but it's too late for that.

**Comment by le0pard** [comment]
@ekr1 as I think, this change was bugfix, because basically without additional configuration js-routes should generate the same routes, as doing rails. Changing configuration change it default behaviour from rails routes, if developer need this.

Also pass one year before someone get some issues with this bugfix. What benefit today will provide notification about change, which was made one year ago?

**Comment by ekr1** [comment]
I can't think of much more than I wrote. If you're dead set on this being OK and no problem, then so be it. Thanks for taking the time to respond.
