### ISSUE TITLE
Locale Question: Custom serializer as named param and not query param

### ISSUE THREAD

**Issue by rpearce** [railsware/js-routes#223]
Thanks for making and maintaining this awesome gem. I'm doing work with it over at https://articulate.com and have a question.

We've got routes such as `/fr-FR/path/to/resource` and `/de-DE/path/to/resource` where the initial route resource is a locale param. Your library handles `Routes.some_path({ locale: 'fr-FR' })` _like a champ_, but I'm trying to extend your custom serializer code in order to add some logic and do this `locale` business in one place. Here's (essentially) what I've come up with:

```rb
JsRoutes.setup do |config|
  config.serializer = <<~'JS'
    function jsRoutesSerializer(object) {
      delete object['locale']
      var prefix = /en/.test(i18next.language) ? '' : i18next.language
      return Routes.default_serializer(object, prefix)
    }
  JS
end

```

Since `i18next` is a global in the app, I've got access to it and can pass it in as a `prefix` while also making sure I delete any `locale` param that is passed in as a param.

Note: I tried to pass the updated `locale` in as a part of `object`, but the result was always `locale` as a search query param (`?locale=es-ES`) and not a proper param (`/es-ES/path/to...`).

Is there a better way to do this? 

* * *

## Edit 1
I now am realizing that overriding the `default_serializer`'s `prefix` actually might not be what I want:
```js
Routes.default_serializer({ abc: 123 }, 'xyz')
// "xyz%5Babc%5D=123"
```

There must be another way...

* * *

## Edit 2
Aha! `Routes.options.prefix` is something that I can change. Is there any way to provide a default for a param instead of setting a prefix like this?

```rb
JsRoutes.setup do |config|
  config.serializer = <<~'JS'
    function jsRoutesSerializer(object) {
      if (object.hasOwnProperty('_FORCE')) {
        delete object._FORCE
      } else if (object.hasOwnProperty('locale')) {
        delete object.locale
      }
      return Routes.default_serializer(object)
    }
  JS
end
```
and then some JS somewhere:
```js
Routes.options.prefix = /en/.test(i18next.language) ? '' : '/' + i18next.language
```

**Comment by bogdan** [comment]
Here it is:

``` js
Routes.options.default_url_options = {locale: i18next.language}
```

**Comment by rpearce** [comment]
@bogdan legend.
