### ISSUE TITLE
Check if window.location exists for hostname

### ISSUE THREAD

**Issue by krzysiek1507** [railsware/js-routes#224]
Hi. Should we here use `current_host` instead of `window.location.hostname`? Unfortunately, it doesn't work with server side rendering w/o setting default host.

https://github.com/railsware/js-routes/blob/5f3605a3d227cde86a8f9a3a5b6e172527c84fa5/lib/routes.js.coffee#L280

**Comment by bogdan** [comment]
What is current host? Can you describe an issue in more details?

**Comment by krzysiek1507** [comment]
Hi @bogdan I mean this method:
https://github.com/railsware/js-routes/blob/5f3605a3d227cde86a8f9a3a5b6e172527c84fa5/lib/routes.js.coffee#L290-L291

When we prerender React code with Routes URLs we got error
```Encountered error "TypeError: Cannot read property 'hostname' of undefined" when prerendering App``` because `window.location` is not present during server side rendering.

**Comment by le0pard** [comment]
@krzysiek1507 but `has_location` should prevent this, isn't it?

UPD:

maybe problem, that should be 

`typeof window isnt 'undefined' && typeof window.location isnt 'undefined'`

**Comment by le0pard** [comment]
@krzysiek1507 how about this branch - https://github.com/railsware/js-routes/pull/225 does it fix this problem?
