### ISSUE TITLE
Optional parameter before required breaks route generation

### ISSUE THREAD

**Issue by gyfis** [railsware/js-routes#231]
We have an optional parameter in our path before a required one - **(:locale)** before **:slug**. When we include both the required parameter and the option hash in the path function while leaving out the first optional parameter, it fails with `ParameterMissing`. This doesn't happen for paths where there is no optional parameter before a required one.

Example path (generated by `JsRoutes.generate!`):
```
...
// blog_post => (/:locale)/blog/:slug(.:format)
// function(slug, options)
blog_post_path: Utils.route([["locale",false],["slug",true],["format",false]], {}, [2,[1,[2,[7,"/",false],[3,"locale",false]],false],[2,[7,"/",false],[2,[6,"blog",false],[2,[7,"/",false],[2,[3,"slug",false],[1,[2,[8,".",false],[3,"format",false]],false]]]]]]),
...
```

This works:
```
> Routes.blog_post_path("my-awesome-slug")
"/blog/my-awesome-slug"
```

This fails while it should've skipped the optional parameter (the same way as the above, only with including the option).
```
> Routes.blog_post_path("my-awesome-slug", {foo: 'bar'})
ParameterMissing {message: "Route parameter missing: slug"}
``` 

However, adding the optional param (`locale`) to the options object seems to work again.
```
> Routes.blog_post_path("my-awesome-slug", {foo: 'bar', locale: 'es'})
"/es/blog/my-awesome-slug"
```

**Comment by bogdan** [comment]
I tried this route in rails and it also raises an error:

``` 
ActionController::UrlGenerationError: No route matches {:action=>"foo", :controller=>"foo", :foo=>"bar", :locale=>"my-awesome-slug"}, missing required keys: [:slug]
```

Rails v5.1.3.

Can you ensure there is an incompatibility in behavior between Rails and JsRoutes?

**Comment by gyfis** [comment]
I understand that Rails require the use of keyword arguments, which is not the same as the functions generated by JsRoutes. 

We also tried to fill in all the arguments as js object (keyword arguments), and that did not work for some use-cases. Below is an example.

This works correctly for all kinds of optional arguments:
```
// blog_post => (/:locale)/blog/:slug(.:format)
...
Routes.blog_post_path({slug: 'my-awesome-blog', format: 'json'})
"/blog/my-awesome-blog.json"
...
Routes.blog_post_path({slug: 'my-awesome-blog'})
"/blog/my-awesome-blog"
...
Routes.blog_post_path({slug: 'my-awesome-blog', locale: 'es', format: 'json', x: 3})
"/es/blog/my-awesome-blog.json?x=3"
```

However, this does not work:
```
// user_page => /user/:id(.:format)
...
Routes.user_page_path({id: 3})
"/user/3"
...
Routes.user_page_path({id: 3, format: 'json', x: 3})
"/user/3"    <------ !!!
```

It seems that when there is no optional param before required param, the generated route does not meet the expectation. This is an assumption, and possibly a different issue.

**Comment by bogdan** [comment]
It looks like a true bug.... I will think about the fix.

**Comment by bogdan** [comment]
The problem with that route is described here: https://github.com/railsware/js-routes#object-and-hash-distinction-issue

In your case, to get the correct route pass `_options` special key:

``` js
Routes.user_page_path({id: 3, format: 'json', x: 3, _options: true})
```

**Comment by gyfis** [comment]
Thanks for the swift reply. If I understand it correctly, we should replace all our calls to Routes with `_options: true` and use that in the future to be solid? Do you think there might be another way or approach on how to solve these issues?

**Comment by bogdan** [comment]
We were thinking about it for a long time and didn't find any solution: JS treats hashes and objects in the same way.

On your end, I would rather use  `user_page_path(3, format: 'json', x: 3)`. I don't know what was the reason to push required parameters as options in the first place.

**Comment by gyfis** [comment]
Using `user_page_path(3, format: 'json', x: 3)` raises `Uncaught SyntaxError: missing ) after argument list`. Writing it as `user_page_path(3, {format: 'json', x: 3})` is getting back to the original issue described in this thread. I'm not really sure if there is another option to use that works instead of writing everything to the `options` object with the `_options: true`.

**Comment by bogdan** [comment]
> Writing it as user_page_path(3, {format: 'json', x: 3}) is getting back to the original issue described in this thread

I can not reproduce that. Which version of rails do you use?

**Comment by gyfis** [comment]
This happens in `JsRoutes`, not Rails. Sorry for the confusion.

**Comment by bogdan** [comment]
That doesn't change my question. In order to confirm the bug you need to give me a call outputs one thing in rails and other thing in JsRoutes.  And that should not be the one caused by Hash <-> Object indistinction issue of JS

**Comment by gyfis** [comment]
I'll try to summarize our issues and solution.

For this path and params, JsRoutes and Rails behave differently.
```
get '/(:locale)/blog/:slug', to: 'blog#show', as: :blog_post
// blog_post => (/:locale)/blog/:slug(.:format)
```
`Rails`
```
> app.blog_post_path("slug")
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"blog", :locale=>"slug", :slug=>nil} missing required keys: [:slug]
```
`JsRoutes`
```
> Routes.blog_post_path("slug")
"/blog/slug"
```
However, with adding options `JsRoutes` raises error as well. Because we want to use other options, we need to move `slug` to options and enable `_options: true`. 

That means that for paths with `/(:locale)`, we need to move all keys to `options` object, and for paths without `/(:locale)`, we can either pass the parameters directly (e.g. `blog_post_path("slug")`) or use the `options` object.

Because we want to be consistent in our usage of `JsRoutes`, we decided to use the `options` object path with `_options: true`. I think most of our confusion was created by the inconsistency of the parameter handling (described in the initial comment here).

Thanks for all the help, feel free to close the issue if you feel like that is not worth fixing.

**Comment by bogdan** [comment]
I can not reproduce that. Which version of Rails do you use?

I didn't understand that part after "However". Can you describe it in the same way as you described the part before "However".

**Comment by gyfis** [comment]
We use Rails `4.2.7.1`.

What I meant by the "However" part is
```
> Routes.blog_post_path("slug", {x: 3})
```
raises error in the same way Rails do.

**Comment by bogdan** [comment]
I still can not reproduce that bug. Are you sure you are using latest `js-routes`?

Regarding "However" part: this is by design - JsRoutes should behave the same way Rails does even when Rails is doing something weird. We can not invent our own spec how routes helpers should work.
