### ISSUE TITLE
JsRoutes do not re-compile when routes.rb changes

### ISSUE THREAD

**Issue by adamrunner** [railsware/js-routes#232]
We have a large scale production application that uses JS Routes heavily for all of the javascript paths. We have an "advanced" setup since we separate out our admin and non admin routes. 

We have 2 `routes.js.erb` files configured to get parsed and then compiled as part of the asset compilation process. 

However, what I've discovered is that when the routes change; the file does not get regenerated (unless it is removed from the sprockets cache). If I add any comments at the top of the `routes.js.erb` file; it gets reprocessed. 

This seems like an order of operations issue; like sprockets is calculating the fingerprint / cache information of the file before ERB is changing the actual contents of the file.

**Comment by bogdan** [comment]
I don't see a way to make that automatic.
JsRoutes can not guess the asset name that needs to be recompiled when `routes.rb` changes.  

The way we can change that is by passing asset name into generate manually:

``` erb
<%= JsRoutes.generate(asset_name: 'admin_routes.js.erb', ... %>
```

It will help JsRoutes to add a dependency to expire the asset by updates in `routes.rb`. 

The alternative way would be specify dependency yourself, but I don't know how to do that yet:

``` js
// = depend_on config/routes.rb
<%= JsRoutes.generate %>
```

I will research for other ideas and post updates.

**Comment by adamrunner** [comment]
For what it's worth, I'd also be ok writing a step in our deploy process that will remove the sprockets cached version of the file and force it to be generated; I can't imagine that enumerating the routes is all that computationally expensive.

**Comment by ElMassimo** [comment]
In case you are looking for a similar library that auto-generates path helpers when a new route is added, check [`js_from_routes`](https://github.com/ElMassimo/js_from_routes#how-does-it-work-%EF%B8%8F).

**Comment by bogdan** [comment]
Webpacker + automatic updates setup is now in Readme. I checked them persnonally an they did work on a fresh rails project. Please open another issue if you have any other problems.

Ideally, you'd also need to upgrade to v2.0.
