### ISSUE TITLE
Webpacker support

### ISSUE THREAD

**Issue by lourenci** [railsware/js-routes#234]
Is there a way to load routes.js file throught webpacker?

**Comment by bogdan** [comment]
Currently there is no way to make routes.js update automatically with webpack. You should either switch to static file and update it manually with rake task or include it separately via  sprockets:

```
= javascript_include_tag 'js-routes'
```

**Comment by lourenci** [comment]
I solve this in my project in a different way:
I changed the config file to export the generated routes file to the webpack javascript path. In my entry file, I used the expose-loader to put it on global object.

**Comment by jorisvh** [comment]
The routes will be assigned to `this`, so this is what my module looks like : 

```
var routes = {};

(function() {
    <%= JsRoutes.generate(namespace: "Namespace") %>
}.call(routes));

export default routes.Namespace;
```

**Comment by jorisvh** [comment]
I just created a file with the extension `.js.erb` and I import it in my packs. Webpacker compiles the erb just like Sprockets does.

But yes, the compiled file won't be updated automatically on each route change (our ugly trick is actually to update the first line of the file with a comment containing the current time each time we change our routes). If you have any idea how to dispense with that, that would make my day !

**Comment by padi** [comment]
@jorisvh Thanks you for the explanation I've since improved upon it. Your timestamp comment is not far off from the solution to the auto-update problem you were having. If you're referring to `bin/webpack-dev-server`'s hot reloading, you can add a magic comment that watches a file for changes!, i.e.:

```
/* rails-erb-loader-dependencies ../config/routes */
var routes = {};

(function() {
    <%= JsRoutes.generate(namespace: "Namespace") %>
}.call(routes));

export default routes.Namespace;
```

This will watch for changes in `config/routes.rb`🥂 🎉 

For more info, just check out [rails-erb-loader](https://github.com/usabilityhub/rails-erb-loader#dependencies), which webpacker uses under the hood.

**Comment by dkniffin** [comment]
@padi Thanks so much for that add-on to the solution. This is all great! I wanted to add a little more info for clarity:

1. You'll need to install `.erb` support in webpacker: `bundle exec rails webpacker:install:erb` [source](https://github.com/rails/webpacker#erb)
2. You'll probably want to add `.js.erb` to the list of extensions in `config/webpacker.yml`
3. Create a file in `app/javascript` called `routes.js.erb` with the above code.
4. In your ES6 code, import it like you normally would with `import '../routes'`
