### ISSUE TITLE
adding data-method="delete" for delete routes

### ISSUE THREAD

**Issue by DrevanTonder** [railsware/js-routes#236]
Currently I am using devise and I have a signout link:
```html
<a href="routes.destroy_user_session_path()">Signout</a>
```
This gives an error when I click on the link: `No route matches [GET] "/users/sign_out"`

So I had to add `<a href="routes.destroy_user_session_path()" data-method="delete">Signout</a>` to get this to work.

It would be nice if this was not necessary to do.

**Comment by bogdan** [comment]
I don't think there is a way of doing that inside js-routes. You should probably ask World Wide Web Consortium to have a new version of HTML that would support that.
