### ISSUE TITLE
Object with keys not resolved to parameters

### ISSUE THREAD

**Issue by andychong1996** [railsware/js-routes#242]
Hi, I'm facing the problem that the object with parameter keys passed was not resolved according to the parameter key, but instead, it was taken as an array of parameter values.

Example:

I have configured the default locale parameter:
```javascript
Routes.configure({
  default_url_options: { locale: "en" }
})
```

And here's one of the path
```javascript
Routes.store_managers_return_path
ƒ /:locale/store_managers/returns/:id(.:format)
```

What I expect:
```javascript
Routes.store_managers_return_path(id: 12)
#or
Routes.store_managers_return_path({id: 12})
#or
Routes.store_managers_return_path({id: 12, locale: 'en'})
#or
Routes.store_managers_return_path(id: 12, locale: 'en')
```
output: `/en/store_managers/returns/12`

What I get:
`Uncaught Error: Route parameter missing: id`

But if I pass in the parameter like this:
```javascript
Routes.store_managers_return_path('en', 12)
```
Then I get the right output: `/en/store_managers/returns/12`.

**Comment by bogdan** [comment]
The reason is clearly explained here: https://github.com/railsware/js-routes#object-and-hash-distinction-issue
Pass `_options: true` to all of your calls to make it work.

**Comment by andychong1996** [comment]
Alright! Thanks for the help! 👍
