### ISSUE TITLE
Current path

### ISSUE THREAD

**Issue by afuno** [railsware/js-routes#249]
I use your library with Webpack (inside the Vue components):

```vue
<template>
  <a :href="$railsRoutes.posts_path()">
    Posts
  </a>
</template>
```

Is there any way to know if the path specified in the link is current?

**Comment by bogdan** [comment]
I believe that you need this: `$railsRoutes.posts_path() == window.location.pathname`

Overall, I don't see that as a feature of JsRoutes.

**Comment by afuno** [comment]
@bogdan Thanks. I will try this option.
