### ISSUE TITLE
Why routes are not updated in production?

### ISSUE THREAD

**Issue by afuno** [railsware/js-routes#250]
Rails 5.2.3 / Ruby 2.6.3 / js-routes 1.4.7

After deployment, the .js file contains old routes, but no new ones. For local development (environment) need to use this command:

```
rails tmp:cache:clear
```

But what to do with the application deployed on the server?

**Comment by afuno** [comment]
Earlier, I did the deployment, which was the first with your gem. Then I added new routes to routes.rb. And in all the new deployments of these routes in the .js file is not. But there are old ones.

**Comment by le0pard** [comment]
Rails 5.2.3
Ruby 2.6.3
js-routes 1.4.7

Using assets pipeline with `//= require js-routes`. 

Deployed by capistrano.

Such issue not reproduced after deploy.

**Comment by afuno** [comment]
@le0pard Very strange.

I have a slightly different chain of directories in assets, but this should not break anything.

app/assets/javascripts/public/footer/base.coffee:

```coffee
#= require rails-ujs

#= require teacher/footer/routes
#= require teacher/footer/global
```

app/assets/javascripts/public/footer/routes.js.erb:

```erb
<%= JsRoutes.generate(namespace: 'RailsRoutes', include: [/teacher/], exclude: [/api/]) %>
```

**Comment by afuno** [comment]
@le0pard Very strange.

I have a slightly different chain of directories in assets, but this should not break anything.

app/assets/javascripts/public/footer/base.coffee:

```coffee
#= require rails-ujs

#= require public/footer/routes
#= require public/footer/global
```

app/assets/javascripts/public/footer/routes.js.erb:

```erb
<%= JsRoutes.generate(namespace: 'RailsRoutes', include: [/public/], exclude: [/api/]) %>
```

**Comment by le0pard** [comment]
If this is your custom js configuration, how do you "explain" assets pipeline calculate hash sum not only by your js.erb file content (which not changed over time - it is the same code), but depend it from rails routes? I did not see `depend_on` at your code.

**Comment by afuno** [comment]
@le0pard I am sorry, but I did not fully understand. I realized that there is a dependency on changes in the routes.rb file. But I did not understand what I did wrong.

My implementation seems to match your example:

```erb
# app/assets/javascripts/admin/routes.js.erb
<%= JsRoutes.generate(namespace: "AdminRoutes", include: /admin/) %>
```

**Comment by le0pard** [comment]
> But I did not understand what I did wrong.

You did not describe this dependency in your file. Example: https://github.com/railsware/js-routes/issues/232#issuecomment-348921974

**Comment by afuno** [comment]
@le0pard 

app/assets/javascripts/public/footer/routes.js.erb:

```erb
// = depend_on config/routes.rb
<%= JsRoutes.generate(namespace: 'RailsRoutes', include: [/public/], exclude: [/api/]) %>
```

```
couldn't find file 'config/routes.rb'
```

**Comment by le0pard** [comment]
It is not working example (it is written in comment), because we don't know which path is used by assets pipeline to resolve dependencies. So you need to find this yourself.

P.S. If this is just one routes file, why don't you use [configuration](https://github.com/railsware/js-routes#configuration) and just `//= require js-routes` in manifest file?

**Comment by afuno** [comment]
@le0pard 

> P.S. If this is just one routes file, why don't you use configuration and just //= require js-routes in manifest file?

I have several (name)spaces. I wanted to split for each space.

---

Now I tried to do it globally. The configurations I wrote in the `config/initializers/jsroutes.rb file`:

```ruby
JsRoutes.setup do |config|
  config.namespace = 'RailsRoutes'
  config.include = [/public/]
  config.exclude = [/api/]
end
```

app/assets/javascripts/public/footer/routes.coffee:

```coffee
#= require js-routes
```

1. I did not change the routes.rb file. Made a deployment. All routes are present in the .js file.
2. I added a new resource in the routes.rb file. In development, he appeared. Made a deployment. New routes are present in the .js file.
3. In the routes.rb file, I deleted a new resource. In development, he disappeared. Made a deployment. New routes were removed from the .js file.

Apparently everything works as it should.

**Comment by le0pard** [comment]
problem resolved
