### ISSUE TITLE
How to install on Rails 6?

### ISSUE THREAD

**Issue by afuno** [railsware/js-routes#252]
In Rails 6 all JavaScript code goes through in webpack.

**app/javascript/packs/application.js:**

```js
require("js-routes")
```

> Module not found: Error: Can't resolve 'js-routes' in '/app/javascript/packs'

**Comment by le0pard** [comment]
@afuno https://github.com/railsware/js-routes/issues/237 - duplicate

**Comment by afuno** [comment]
@le0pard I'm not sure that it is a duplicate.

**Comment by le0pard** [comment]
@afuno rails 6 using something different, that webpacker?

**Comment by afuno** [comment]
@le0pard In general, everything was correctly described in that issue. But...

I created a file:

```erb
// app/javascript/rails/js_routes.js.erb

<%= JsRoutes.generate() %>
```

Added it to `application.js` file:

```js
import RailsRoutes from '@rails/js_routes.js'
// or
// import RailsRoutes from '@rails/js_routes.js.erb'
// but not
// import RailsRoutes from '@rails/js_routes'
```

After that a problem appeared - bundle from webpack is not generated. That is, as usual, I launch the application. Rails starts, but the page does not load (long wait and break):

> 22:13:12 webpacker.1 | ℹ ｢wdm｣: wait until bundle finished: /packs/js/application-bf8m2772ffd0d10db4fa.js

> GET http://localhost:3120/packs/js/application-bf8m2772ffd0d10db4fa.js net::ERR_ABORTED 500 (Internal Server Error)

**Comment by afuno** [comment]
@le0pard Thank you.
