### ISSUE TITLE
How to set default_url_options correctly?

### ISSUE THREAD

**Issue by afuno** [railsware/js-routes#254]
A simple example from the Rails documentation contains this code:

```ruby
def default_url_options
  { locale: I18n.locale }
end
```

And it successfully works with `*_path` Rails helpers.

But I have a sufficient number of links formed in Vue components. To do this, in the app.js file, I include the file with the `JsRoutes` setting:

```js
import railsRoutes from '@public/rails/js_routes.js.erb'
```

```erb
<%= JsRoutes.generate(
  default_url_options: {
    locale: I18n.locale
  },

  include: [
    # ...
  ],

  exclude: [
    # ...
  ]
) %>
```

As a result, I have links with default locale formed in Vue components.

Running this command didn't help:

```
rails tmp:cache:clear
```

Tell me, please, what have I done wrong?

**Comment by afuno** [comment]
That is, in the address bar of the browser, I have this:

```
http://localhost:3010/albums?locale=ru
```

All Rails helpers generate links of this kind:

```
http://localhost:3010/images/2374?locale=ru
```

But helpers inside JS give this:

```
http://localhost:3010/posts?locale=en
```

**Comment by le0pard** [comment]
Common Modules cached in webpack build system:

```
import railsRoutes from '@public/rails/js_routes.js.erb'
```

will be cached and evaluated on build. 

Also:

```
<%= JsRoutes.generate(
  default_url_options: {
    locale: I18n.locale
  },

  include: [
    # ...
  ],

  exclude: [
    # ...
  ]
) %>
```

will be executed once and system will not `generate` for each request new js routes. 

From your integration you will build only js routes for some default locale.

**Comment by afuno** [comment]
@le0pard Thanks for the answer.

And can I somehow replace my ERB file with JS? That is, can I somehow work with JsRoutes directly in JS?

I saw this example in your documentation:

```js
Routes.configure({
  option: value
});
Routes.config();
```

But I don't understand how to apply this in Rails 6. In Rails 6, all of JS is given to Webpacker. I understand that can use the old structure, but I would not want to.

**Comment by le0pard** [comment]
> And can I somehow replace my ERB file with JS?

Yes, you can pregenerate erb to js file and import in this case generated static JS file.

> That is, can I somehow work with JsRoutes directly in JS?

You can work directly with JS routes, even in your example:

```
import railsRoutes from '@public/rails/js_routes.js.erb'

// work directly with railsRoutes
```

Because even erb file in end will be JS file, where you can work directly with it.

**Comment by afuno** [comment]
@le0pard Thank you so much. Everything worked out.
