### ISSUE TITLE
sprockets 3.7.2 is not working

### ISSUE THREAD

**Issue by vignesh-drg** [railsware/js-routes#255]
I am using in my application sprockets 3.7.2 and getting the below error,
DEPRECATION WARNING: You are using the a deprecated processor interface #<Proc:0x007fd4091c3470@/shared/bundle/ruby/2.1.0/gems/js-routes-1.1.2/lib/js_routes/engine.rb:9>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Engine> at /bundle/ruby/2.1.0/gems/js-routes-1.1.2/lib/js_routes/engine.rb:9)
DEBUG [b459bb68] 	DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /bundle/ruby/2.1.0/gems/sass-rails-5.0.4/lib/sass/rails/railtie.rb:57)
DEBUG [b459bb68] 	DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors

I am using ruby 2.1.5 and rails 4.2
Can you please help me out with the issue

**Comment by le0pard** [comment]
In your logs no errors, only deprecation warnings.

**Comment by vignesh-drg** [comment]
Sorry, My deployment getting failed after the warning message and though this could be the issue.
