### ISSUE TITLE
Assignment inside if operand.

### ISSUE THREAD

**Issue by vdv73rus** [railsware/js-routes#260]
In the generated routes js file I've found such code (and some code quality utils show the error)
```
if ((url_params = this.serialize(parameters)).length) { …
```

It means that we are doing the assignment inside `if` operand. Don't think it is correct or what the logic here? Maybe it is a bug or just a wrong compile result from coffee script?

**Comment by le0pard** [comment]
@vdv73rus why assignment in `if` is not correct, if `if` checks value `length`, not assignment?

**Comment by vdv73rus** [comment]
It is not a good pattern to do an assignment inside the `if` operator. It is better to do the assignment and checking separately.
```
const url_params = this.serialize(parameters);
if (url_params.length) { …
```

**Comment by le0pard** [comment]
@vdv73rus coffescript compiler did this in such way. It did not break anything and doesn't have side effects. So not clear what the issue.

**Comment by vdv73rus** [comment]
Yes, you are right, but codacy code quality service says me that something is not good

![image](https://user-images.githubusercontent.com/971061/93883146-3c2ba580-fcf2-11ea-9791-581970516233.png)

**Comment by le0pard** [comment]
@vdv73rus it just talking about "harder to read". It is more "personal preferences", not something about "consistency in codebase" or "performance issue" or "possible issues with some arguments".

**Comment by vdv73rus** [comment]
@le0pard So what is your suggestion?
Change the code manually? — bad idea, because the file is autogenerated.
Switch off the rule? — in this case we'll not see the real errors in other parts of the project

**Comment by vdv73rus** [comment]
But we can try to ignore `routes.js` for any types of checking. Seems it possible solution

**Comment by le0pard** [comment]
@vdv73rus why this tool checks vendor/3-rd part libraries code? should it skip external dependencies and check only own project codebase?

**Comment by vdv73rus** [comment]
Sure, we've found the setting which ignores this file. Close the issue
