### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by wwahammy** [railsware/js-routes#261]
This gem is very cool and im excited to use it. One thing that I could use is the option of generated the Route object as Typescript. That would make guarantee that I'm at least passing the correct parameters when I try to generate a path. Would you be open to a PR to add an option for generating the Routes object in Typescript?

**Comment by bogdan** [comment]
Yes, I am open. Currently the project is written in CoffeeScript that compiles to JavaScript. The decision was made long ago and I considered it a good idea at that moment. However, if I would make the lib today, I would definitely choose TypeScript for the job.

Here are some implementation concerns I would raise:

* Be able to setup output format for routes:
  * Javascript (I think should be kept as default)
  * Typescript
  * Typescript Definitions (`.d.ts`)
* Add tests for type-checked route calls

**Comment by wwahammy** [comment]
Awesome. I'll probably start working on that today a bit.

Also this explains why the coffeescript file is there! 😃 I was kind of confused but figured there was a good reason.

Also, is there some sort of build step in the repo that compiles the coffeescript file into javascript?

**Comment by bogdan** [comment]
There is: https://github.com/railsware/js-routes/blob/18c7bd0c06bd1805553e37aedfef0cfb75d12e56/spec/spec_helper.rb#L84

I actually don't know why it is only happening when running specs. I didn't do it myself and that seems not so right to me, but on the other hand it was working well for years. I am fine if it will be kept like that or reworked if it is more convenient to do it other way.

**Comment by wwahammy** [comment]
Hmmm, interesting.

Unless there's a strong reason not to, I think it'd make sense to use a standard Javascript package.json and use Babel to get the compiled version. What do you think?

**Comment by bogdan** [comment]
Hehe... even if "standard Javascript package.json" did exist at the moment when we built it, it wasn't a "standard" for sure.

Yes, that will work. I am not sure what babel would add on top of typescript itself though: typescript can compile to ES5 easily using `target` option. Why would you need babel?

**Comment by wwahammy** [comment]
> Hehe... even if "standard Javascript package.json" did exist at the moment when we built it, it wasn't a "standard" for sure.

To be clear, I certainly did not intend this as a criticism! I think the software is amazing

> Yes, that will work. I am not sure what babel would add on top of typescript itself though: typescript can compile to ES5 easily using `target` option. Why would you need babel?

The big thing we'd gain with babel would be polyfills and the like for APIs which aren't available in older browser *cough* IE11 *cough*. I was attempting to use some newer features to simplify some of the typescript code but now that I think of it, I could just not do that, and we could just use `tsc` by itself. We might even be able to use `tsc` via npx and we wouldn't even need to have a `package.json` or `node_modules`.

**Comment by bogdan** [comment]
> To be clear, I certainly did not intend this as a criticism! I think this software is amazing.

No, no, I wrote that with a smile and to say how times change and things that were a good idea 7 years ago are looking weird or at least not very standard anymore. 👍 

As far I know `target` option for `tsc` just does the polyfil. We used that in one of our open source browser libs and it worked fine. I am not sure what babel can add on top.

`package.json` can be a good idea because it helps people to setup env if they don't know what to do. In our compile script we can try to search for `tsc` through `npx` or from `node_modules/.bin/tsc` whatever exists.

**Comment by ElMassimo** [comment]
In case you are looking for something similar, check out [`js_from_routes`](https://github.com/ElMassimo/js_from_routes#file_suffix-default-requestsjs), which can be tweaked to generate TypeScript, and plays nicely with code-splitting and ESM imports.

**Comment by bogdan** [comment]
Released version 2.1.0 with the support. See Readme.md for more info. It may contain bugs, so feel free to open an issue.

**Comment by wwahammy** [comment]
Thanks a ton @bogdan! I'll check in out in the next few days!
