### ISSUE TITLE
Routes not defined error

### ISSUE THREAD

**Issue by jimdwyerdev** [railsware/js-routes#263]
https://github.com/railsware/js-routes/blob/4ac6987adf2526705d2da796797c86746ec138f1/lib/js_routes.rb#L14

In this recent change, if webpacker is installed then the namespace will be nil and creates an error. Is this an intentional change? 

Was able to fix by adding:
`config.namespace = "Routes"`

Is there a different way to be referencing the routes namespace if Webpacker is installed?

Thanks in advance!

**Comment by bogdan** [comment]
The different way would be to use `import Routes from '<path>/routes` wherever you need routes. Keeping things organized and continue discussion on https://github.com/railsware/js-routes/issues/237.
