### ISSUE TITLE
Migrating from version 1.4.9 to 1.4.14 doesn't generate Routes anymore

### ISSUE THREAD

**Issue by roberts-eihmanis** [railsware/js-routes#270]
Hey,

Using js-routes version 1.4.9.
Rails 5.2.4.5
Ruby 2.5.3
Webpacker 3.6.0
Node version 10.14

This is my setup.
```
import tenant from './tenant.js'

<%= JsRoutes.generate %>

this.Routes.configure({
  default_url_options: {
    tenant: tenant()
  }
})

export default this.Routes
```

Have an update currently to 1.4.14, but it doesn't seem to work anymore.
Tried the setup what is in the README, but still can't get it going.
Currently trying with `rake js:routes` with `routes.js` and `<%= JsRoutes.generate() %>` with `routes.js.erb`,
But the result is the same in both cases, it kinda imports the Routes object, but the Routes object, which is imported, just shows:
![Screenshot 2021-04-29 at 14 37 11](https://user-images.githubusercontent.com/3621020/116544960-76989900-a8f8-11eb-813f-68f092fe27f5.png)
![Screenshot 2021-04-29 at 14 37 26](https://user-images.githubusercontent.com/3621020/116544971-7ac4b680-a8f8-11eb-95a5-701ae4bb16f9.png)

Currently trying to update all of the systems packages, but as this is the first package that was in the list of updating (using depfu), then can't actually go any further. Maybe I need some newer webpacker or newer rails for this?

Would appreciate any help,
Thanks.

**Comment by bogdan** [comment]
`1.4.14` uses a more strict typing. You can use the older schema like `<%= JsRoutes.generate(namespace: 'Routes')` or (preferred):

``` js
const Routes = <%= JsRoutes.generate %>
```

**Comment by roberts-eihmanis** [comment]
Thanks, this was easy
