### ISSUE TITLE
config.include regExes should match the camelCased route names now

### ISSUE THREAD

**Issue by OtherCroissant** [railsware/js-routes#276]
In the new version, the config.include (and probably config.exclude) seem to match the camelCased base_names of the routes. Previously, these filters worked based on the underscored Route names, as used in Rails. Nowadays (I am not currently sure which version changed this), I have to rewrite this filter to camelCased regexes.

For example:

```
  config.include = [
    /^admin$/,
    /^admin_front_page$/,
    /^not_your_average_admin_front_page$/
```
should be rewritten to:

```
  config.include = [
    /^admin$/,
    /^adminFrontPage$/,
    /^notYourAverageAdminFrontPage$/
```

I don't really mind this change, but for other users, it could be a breaking change.

Also I guess that this example of the readme does not work any longer because it tries to match on the underscore:
```
JsRoutes.generate!("#{path}/app_routes.js", exclude: [/^admin_/, /^api_/])
JsRoutes.generate!("#{path}/adm_routes.js", include: /^admin_/)
JsRoutes.generate!("#{path}/api_routes.js", include: /^api_/, default_url_options: {format: "json"})
```

Maybe you could also include an example with a larger path?

**Comment by OtherCroissant** [comment]
So, I guess it was a bug? thanks for the rapid fix!

**Comment by bogdan** [comment]
Yes, I had no intent to change that and I don't see any reason why new way is better than the old. Overall I don't like how  `include/exclude` options are working. They should really apply to route spec like `/admin/posts/:post_id` instead of helper name, but that is a story for another time.
