### ISSUE TITLE
Compatibility with Vite

### ISSUE THREAD

**Issue by nickcotton** [railsware/js-routes#278]
Hi! I've recently been exploring migrating our rails app from webpack/webpacker to Vite.

I'm getting an error whenever I try to import a specific route. I do not get the same error when using webpacker.

`import { plannerAdminPagePreviewPath } from "@/app/javascript/routes";`

`undefined is not an object (evaluating 'object[part] = routes')`

<img width="507" alt="CleanShot 2021-06-04 at 09 09 26@2x" src="https://user-images.githubusercontent.com/213528/120769003-9a14bc00-c514-11eb-92e2-5982b2c6a457.png">

I've seen similar errors mentioned before but not in relation to Vite.

Do you know if I'm missing something? Is there a config step I've left out? Thanks!

**Comment by bogdan** [comment]
Set `namespace = nil` in your Js routes configuration file. That should help. If not, consider upgrade to 2.x.

**Comment by nickcotton** [comment]
Thanks, that worked! For anyone else that comes across this, I was using 2.x already.

**Comment by bogdan** [comment]
Current 2.x default for `namespace` is this:

```
{
    namespace: -> { defined?(Webpacker) ? nil : "Routes" },
}
```
 
Is there any way I can detect Vite env setup easily and ensure it is `nil` there too?

**Comment by nickcotton** [comment]
I'm not 100% sure. I've been using the https://github.com/ElMassimo/vite_ruby gem to get Vite working but that wouldn't necessarily be true for everyone. Perhaps there's something useful there though.
