### ISSUE TITLE
Cant pass query params to index resource route

### ISSUE THREAD

**Issue by lukasedw** [railsware/js-routes#279]
Don't generate query params to a index resource route: 
![image](https://user-images.githubusercontent.com/13969616/121576320-a27e6280-c9fe-11eb-973f-4ff8ccd8c07c.png)
![image](https://user-images.githubusercontent.com/13969616/121576430-be820400-c9fe-11eb-8534-c7ce604817ac.png)

But when i try to pass to a get or post route:
![image](https://user-images.githubusercontent.com/13969616/121576521-d5c0f180-c9fe-11eb-8150-92098d233c60.png)
![image](https://user-images.githubusercontent.com/13969616/121576640-f2f5c000-c9fe-11eb-9a11-bac5e2d33991.png)

**Comment by bogdan** [comment]
Remove last `s` from `bases`:

```
Routes.process_activity_base_path({id: 3})
```

**Comment by lukasedw** [comment]
> Remove last `s` from `bases`:
> 
> ```
> Routes.process_activity_base_path({id: 3})
> ```

It is not a record that i am trying to rout. I want to past custom parameters for search, like Routes.process_activity_bases_path({name_eq: 'James'}) -> /process_activity_bases?name_eq=James

**Comment by bogdan** [comment]
Can you report a bug in a more formal way? What do you do, what is your expectation, what is is a thing you actually get?

https://gist.github.com/carlo/3402842
