### ISSUE TITLE
how to get root_path

### ISSUE THREAD

**Issue by jubilee2** [railsware/js-routes#280]
how to get root_path?

**Comment by le0pard** [comment]
https://github.com/railsware/js-routes/blob/master/spec/js_routes/rails_routes_compatibility_spec.rb#L133

**Comment by jubilee2** [comment]
> https://github.com/railsware/js-routes/blob/7e32ac5644d9ab0d496a124108ebcd00d99d864c/spec/js_routes/rails_routes_compatibility_spec.rb#L158

Thank you
