### ISSUE TITLE
Don't know how to build task 'js:routes'

### ISSUE THREAD

**Issue by jefflyne** [railsware/js-routes#283]
Following the installation and quickstart instructions, it doesn't find the rake task.  Am I missing something?  I'm using rails 6.1.4.

**Comment by bogdan** [comment]
Run the following sequence of commands and see if you do something differently:

``` sh
rails --version
rails new js-routes-test
cd js-routes-test
bundle add js-routes
rake js:routes
tail app/javascript/routes.js
```

It works perfectly fine on my end. Here is the log:
https://gist.github.com/bogdan/6efdb7e8ff10384823c2263aa34f944a

**Comment by bogdan** [comment]
No respose  - closing. Feel free to follow up and reopen.

**Comment by GyozaGuy** [comment]
I'm experiencing the same issue, also using Rails 6.1.4. Oddly enough I installed js-routes in one app a couple days ago with no issues, but when trying to install it in another project using the same versions of Ruby and Rails, the rake task isn't found. Following the steps above works fine, but adding js-routes to this one project of mine doesn't seem to create the rake task.

**Comment by bogdan** [comment]
You may try to compare your `Rakefile` to the `Rakefile` generated by `rails new`. Maybe there is something different that requires an update.

**Comment by GyozaGuy** [comment]
I did so, both of my apps are pretty simple so the `Rakefile` is still identical to that in a new Rails app:
```ruby
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks
```

**Comment by bogdan** [comment]
The problem can be in the require. You can try the following:

* put `puts JsRoutes` after `require_relative` and make sure `JsRoutes` was required
* Debug `load_tasks` call and see what's inside and where JsRoutes is missing

**Comment by GyozaGuy** [comment]
Your comment about checking to see what was required inspired me to check the contents of `config/application.rb`, and turns out there were differences between my two apps. The slightly older app (which didn't work with js-routes) contained this at the top of the file:
```ruby
require 'rails'
# Pick the frameworks you want:
require 'active_model/railtie'
require 'active_job/railtie'
require 'active_record/railtie'
require 'active_storage/engine'
require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'action_mailbox/engine'
require 'action_text/engine'
require 'action_view/railtie'
require 'action_cable/engine'
# require "sprockets/railtie"
require 'rails/test_unit/railtie'
```
Whereas the newer app (that did work with js-routes) contained only this:
```ruby
require "rails/all"
```

I changed the older app to require `rails/all`, and now the js-routes rake task is available. 💯

**Comment by bogdan** [comment]
I think the key thing that actually loads the `JsRoutes` is `Bundler.require(*Rails.groups)` line in `application.rb`. It is hard to imagine that `rails/all` is requiring `js-routes`.

**Comment by GyozaGuy** [comment]
I don't know, but I'm happy it's working!
