### ISSUE TITLE
Typescript doesn't resolve properly the dynamic routes module

### ISSUE THREAD

**Issue by mdesantis** [railsware/js-routes#285]
Hello and thanks for your gem!

Typescript complains about `import * as Routes from 'routes.js.erb'`. After setting up js-routes, when I run  `yarn run tsc -p tsconfig.json --noEmit` in my project I get:

```
> yarn run tsc -p tsconfig.json --noEmit
yarn run v1.22.10
$ rails-jsroutes-bug-repro/node_modules/.bin/tsc -p tsconfig.json --noEmit
app/javascript/packs/hello_typescript.ts:6:25 - error TS2307: Cannot find module 'routes.js.erb' or its corresponding type declarations.

6 import * as Routes from 'routes.js.erb'
                          ~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
```

I made a reproduction app, as I wanted to be sure the error wasn't related to some misconfiguration of my enviroment: https://github.com/mdesantis/rails-jsroutes-bug-repro

**Comment by bogdan** [comment]
I don't see there is any way you can make it work: `.erb` files are not processed by `tsc`. So, if you really need to compile your typescript via `tsc` or just perform the typecheck (aka `--noEmit`), you should switch to static files like so: https://github.com/railsware/js-routes#quick-start

**Comment by bogdan** [comment]
I've updated readme to clarify this issue. I don't believe it can be solved any better at the moment. Feel free to follow up with with suggestions.

**Comment by mdesantis** [comment]
@bogdan sorry for lacking of a prompt reply. It's clear now, thank you, but now I wonder what is the `.d.ts.erb` file for? Did you add it in order to generate the `.d.ts` and it has no other purpose?

**Comment by bogdan** [comment]
I made a mistake introducing `routes.d.ts.erb` file. This file can not be used by IDE or `tsc` because they are unaware of how to process `erb` extension. So I've updated the readme with that note. 

Currently I don't see a way how to use webpacker + automated reloading setup with typescript. You have to switch to static setup described in [Quick Start](/railsware/js-routes#quick-start)

**Comment by mdesantis** [comment]
I understand, now it's perfectly clear. I'm just going to remove it. Thanks for your time!
