### ISSUE TITLE
No default export in Typescript definitions file

### ISSUE THREAD

**Issue by utricularian** [railsware/js-routes#286]
Prior to the Typescript update (which is awesome), I was able to consume my routes file like this:

`import Routes from 'config/backendRoutes'`

Converting the file to Typescript, I now get:

`"export 'default' (imported as 'Routes') was not found in 'file/that/was/generated'`

I can get around this by doing the following:

`import * as Routes from 'config/backendRoutes'`

Is it possible to add a default export in the `.d.ts` file?

**Comment by bogdan** [comment]
This is a part of `ESM` module system: default export makes it impossible to use ESM tree shaking. See https://github.com/railsware/js-routes/blob/master/VERSION_2_UPGRADE.md for more info.

**Comment by bogdan** [comment]
I've added a note that typescript definitions are only capable with ESM module type in Readme. Not much else I can do at the moment.
