### ISSUE TITLE
module_type: nil causes "NIL is not supported by runtime"

### ISSUE THREAD

**Issue by kyrofa** [railsware/js-routes#292]
The README states:

> You can manipulate the generated helper manually by injecting ruby into javascript:
> 
> ```
> export const routes = <%= JsRoutes.generate(module_type: nil, namespace: nil) %>
> ```

However, in practice, for me on version 2.1.2 that leads to an uncaught exception: "NIL is not supported by runtime". Is this bit of the README out of date? Is there still a way to do this?

**Comment by bogdan** [comment]
Yes, it should be supported. Can you give me a full backtrace?

**Comment by bogdan** [comment]
I've tried to fix the issue, but I am not 100% sure why it is there in the first place. Can you try the current master and see if it helps?

**Comment by bogdan** [comment]
No followup, closing.

**Comment by khiemb** [comment]
I'm experiencing this same error, with version 2.2.2
