### ISSUE TITLE
Thoughts for using with webpacker within a Rails engine

### ISSUE THREAD

**Issue by kyrofa** [railsware/js-routes#293]
First of all, this gem is a great idea. It solves a huge pain point. However, most of my projects are fairly modular, broken up into multiple Rails engines. I use webpack for these, and distribute them as both Ruby gems (for the Ruby bits) and node packages (for the webpack'd Javascript bits).

The challenge I'm facing is twofold. 

1. js-routes picks up the dummy project's routes, and I see no way for pointing it at the engine's (**update**: wait, looks like [this is it](https://github.com/railsware/js-routes/blob/master/lib/js_routes.rb#L23)).
2. Engines can be mounted anywhere in the routes, and I don't know where when I'm webpacking the javascript, which includes the routes. In Rails, the route names remain the same no matter where they're nested when they're mounted, but they point to different URLs depending on the mountpoint. In js-routes, even assuming there's a way around (1), the routes have already been compiled. How can they be responsive to different mountpoints?

Assuming this isn't possible today, if we can settle on a design you like, I'd be happy to implement it.

**Comment by bogdan** [comment]
Hey, 

I've never tried anything like that myself and support for engines was implemented by contributor, but guess that you should be able to achieve what you want with the following options:

1. `application` to specify the engine
2. `prefix` to set a mount point.
3. `default_url_options` may also be helpful

**Comment by bogdan** [comment]
No followup, closing.
