### ISSUE TITLE
Custom output path

### ISSUE THREAD

**Issue by beeforever** [railsware/js-routes#296]
This is still not working (app/assets/javascripts/) exists within my rails app:
config/initializers/js_routes.rb:

```
JsRoutes.setup do |c|
  c.module_type = nil
  c.namespace = 'Routes'
  c.prefix = Figaro.env.url_prefix
  c.file = 'app/assets/javascripts/routes.js'
end

rake js:routes
Errno::ENOENT: No such file or directory @ rb_sysopen - PATH/app/javascript/app/assets/javascripts/routes.js
```

_Originally posted by @beeforever in https://github.com/railsware/js-routes/issues/295#issuecomment-1027025552_

**Comment by bogdan** [comment]
You should be using absolute path `Rails.root.join('app/assets/javascripts/routes.js')`. I don't see a way it can get solved with relative path because it is unknown if relative path if from `Rails.root` or `app/javascript`.

**Comment by beeforever** [comment]
OK, thanks
