### ISSUE TITLE
ESM Tree shaking not working because __jsr.r() is potentially impure

### ISSUE THREAD

**Issue by joshwilsonvu** [railsware/js-routes#307]
Thank you so much for maintaining this package! We're using it in my company and are moving to the ESM format in a Webpack setup.

## Problem

I noticed that even though each route is exported individually, the way they are defined prevents Webpack (and other bundlers) from being able to tree-shake unused exports. 

To explain: each export is the result of a function call

```javascript
export const accept_user_invitation_url = __jsr.r({"format":{}}, [2,[7,"/"],[2,[6,"users"],[2,[7,"/"],[2,[6,"invitation"],[2,[7,"/"],[2,[6,"accept"],[1,[2,[8,"."],[3,"format"]]]]]]]]], true);
```

and Webpack can't prove that the function call doesn't have a side-effect (like modifying module/global variables), so it will decide not to remove it, for safety. The way libraries typically deal with this is by adding a `/*#__PURE__*/` [comment](https://webpack.js.org/guides/tree-shaking/#mark-a-function-call-as-side-effect-free) right before the call, to inform the minifier that the call is safe to remove if possible.

## Reproduction

I've created a minimal reproduction [here](https://github.com/joshwilsonvu/js-routes-treeshaking). It contains two nearly identical directories, each with a `src/index.js` that uses only one of the sixteen routes defined in `src/routes.js` (a partial copy of my codebase's much larger file). In each directory, `dist/main.js` is generated from running `yarn build`.

 The `without-pure` directory's `src/routes.js` is what `js-routes` generates today; the `without-pure` directory's `src/routes.js` has been modified to include a `/*#__PURE__*/` comment right before each `__jsr.r()` call. This is the only difference.

In `without-pure`, tree shaking doesn't work; `without-pure/dist/main.js` contains code defining all the routes. Scroll down and you'll see many `r.r()` calls (minified from `__jsr.r`).

In `with-pure`, tree shaking works; `with-pure/dist/main.js` has only one `r.r()` call, and half as many total lines.

## Suggested solution

I think we can add the `/*#__PURE__*/` comment simply by

```diff
    def routes_export
      return "" unless @configuration.modern?
      [*static_exports, *routes_list].map do |comment, name, body|
-       "#{comment}export const #{name}#{export_separator}#{body};\n\n"
+       "#{comment}export const #{name}#{export_separator}/*#__PURE__*/ #{body};\n\n"
      end.join
    end
```

It should only apply to the ESM format. This could break a few tests in `spec/js_routes/module_types/esm_spec.rb`, but those are fixed by adding the `/*#__PURE__*/` comment as appropriate.

I would be happy to submit a pull request to do this. Please let me know if you have any questions or concerns! Thanks again.

**Comment by bogdan** [comment]
Sounds very reasonable. Thanks for your research! 

I see you are using `import * as Routes` in `index.js`. I never thought tree shaking support to be working in such a syntax, however you research does show that it can with `__PURE__` notation. 

It would be a good idea if you also make `without-pure-direct-import` version like:

```
import {accept_user_invitation_url} from './routes';
console.log(accept_user_invitation_url); 
```

However, the fact that we can make tree shaking work for `import *` version is a good thing anyway.
The only down side is a significant increase in the `routes.js` file size especially if someone is importing routes one by one anyway.

The idea solution would be if PURE directive supports opened and closed tags like:

``` js
/*#__PURE__ start*/ 

export const accept_user_invitation_url = __jsr.r({"format":{}}, [2,[7,"/"],[2,[6,"users"],[2,[7,"/"],[2,[6,"invitation"],[2,[7,"/"],[2,[6,"accept"],[1,[2,[8,"."],[3,"format"]]]]]]]]], true);
...

/*#__PURE__ end*/
```

If not, it is hard to say if we should suggest people to migrate from `import *` syntax. I think it can be more convenient for larger files that use 10+ routes. Lets see the result of `without-pure-direct-import` version first.

**Comment by joshwilsonvu** [comment]
Sure, I've added example using named imports instead of `import * as`. See [without-pure-named-import](https://github.com/joshwilsonvu/js-routes-treeshaking/tree/main/without-pure-named-import) and [with-pure-named-import](https://github.com/joshwilsonvu/js-routes-treeshaking/tree/main/with-pure-named-import). 

What I've found from the results is that Webpack treats both cases the same—it can figure out whether each export is used no matter the syntax. Doesn't matter if it's `import *` or `import {}`. So users will **not** need to switch to `import *` or change their code at all!

I'm with you on how awkward it is to add a `/*#__PURE__*/` comment to every _callsite_ of a side-effect-free function. It would be nicer if you could mark that a function is pure once, at its definition. I think this convention was started with Uglify, an early JS minifier, and has stuck around in other tools long after most people have moved onto other tools.

Anyway—have a look at the new examples, and let me know if you'd like me to send a pull request 🙂

**Comment by bogdan** [comment]
Ok, sounds good! I am open for a PR.

A few suggestions on the implementation:

* Lets put `PURE` directive inside `body` method.
* The generator supports different module types. I think `PURE` should only be the case for `ESM` module. It would be good if you double check.
