### ISSUE TITLE
TypeError: Return value: Expected type T.proc.params().returns(T.any(Rails::Application, T::Class[Rails::Engine])), got type Class with value MyEngine::Engine (TypeError)

### ISSUE THREAD

**Issue by shanecav84** [railsware/js-routes#323]
I'm developing an engine using JsRoutes. This was working on 2.2.8 and started not working on 2.2.9.

Configuration:

```ruby
JsRoutes.setup do |config|
  config.application = MyEngine::Engine
end
```

<details><summary>Trace</summary>
<pre>
bin/rails app:js:routes --trace
** Invoke load_app (first_time)
** Execute load_app
** Invoke app:js:routes (first_time)
** Invoke app:environment (first_time)
** Execute app:environment
** Execute app:js:routes
rails aborted!
TypeError: Return value: Expected type T.proc.params().returns(T.any(Rails::Application, T::Class[Rails::Engine])), got type Class with value MyEngine::Engine (TypeError)
Caller: ~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes/instance.rb:121
Definition: ~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes/configuration.rb:35 (JsRoutes::Configuration#application)

    raise TypeError.new(opts[:pretty_message])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/configuration.rb:303:in `call_validation_error_handler'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:318:in `report_error'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:287:in `validate_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes/instance.rb:121:in `application'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `bind_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `validate_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes/instance.rb:28:in `generate'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `bind_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `validate_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes/instance.rb:56:in `block in generate!'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/activesupport/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/activesupport/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/activesupport/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/activesupport/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/activesupport/lib/active_support/lazy_load_hooks.rb:59:in `each'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/activesupport/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/railtie/configuration.rb:71:in `after_initialize'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes/instance.rb:54:in `generate!'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `bind_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `validate_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/js_routes.rb:39:in `generate!'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `bind_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `validate_call'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/js-routes-2.3.0/lib/tasks/js_routes.rake:5:in `block (2 levels) in <top (required)>'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/commands/rake/rake_command.rb:18:in `perform'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/command.rb:51:in `invoke'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/commands.rb:18:in `<top (required)>'
~/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
~/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
~/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rails-df5ac037b1b3/railties/lib/rails/engine/commands.rb:9:in `<top (required)>'
~/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
~/.rbenv/versions/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
bin/rails:24:in `<main>'
Tasks: TOP => app:js:routes
</pre>
</details>

**Comment by bogdan** [comment]
Fixed: regression when specifying the `application` without `-> { ... }` (which is somewhat recommended).

You may wait for the release or use:

``` ruby
JsRoutes.setup do |config|
  config.application = -> { MyEngine::Engine }
end

**Comment by shanecav84** [comment]
Thank you!
