### ISSUE TITLE
How to strip a prefix from all the routes?

### ISSUE THREAD

**Issue by ibrykov-mdsol** [railsware/js-routes#326]
Thank you for an awesome gem!

In our app we have to strip some of the leading parts of all the routes. Right now we simply monkey patch `js-routes` like so:

```
class JsRoutes::Instance
  alias __generate generate
  def generate
    __generate.gsub!(
      "return utils.route(parts_table, route_spec, absolute);",
      "return utils.route(parts_table, route_spec[2][2][2][2], absolute);"
    )
  end
end
```

Obviously, it's not an ideal solution.

So maybe there is actually a way to do that already that I missed?
If there is none, what if we can add an option to the configuration to apply a lambda/proc to all the routes so that we could granularly tweak them any way we want?

**Comment by bogdan** [comment]
It is unclear what you are trying to achieve. 

Can you show your `routes.rb` (maybe an example) and how you use route helper `*_path` on a frontend and what kind of results it gives to you, also how is it different from the result you are getting on backend?

**Comment by ibrykov-mdsol** [comment]
Our `routes.rb` is pretty typical. Just a bunch of nested resources. I cannot share it, NDA, you know. But I'll give you an example of what `rails routes` generates:
```
                                 resource GET    /apps/foo/resources/:id(.:format)                                                                 resources#show
                                         PATCH  /apps/foo/resources/:id(.:format)                                                                 resources#update
                                         PUT    /apps/foo/resources/:id(.:format)                                                                 resources#update
                                         DELETE /apps/foo/resources/:id(.:format)                                                                 resources#destroy
```

As you can see, we have that prefix `/apps/foo` that we have to keep for compliance reasons. But we have to skip that prefix in our FE code. We navigate to `/resources/...`, so `resourcePath('123')` helper has to generate `/resources/123`.

Our monkey patch strips first 2 levels of the routes the helpers generate.

Hope this makes things clear.

**Comment by bogdan** [comment]
> I cannot share it, NDA, you know.

I only need to know how you define the `/apps/foo` namespace, weather it wraps the entirety of routes or just part of them.

> As you can see, we have that prefix /apps/foo that we have to keep for compliance reasons

Well, it seems that rails is pretty clunky at configuring relative url root.
There are a few options that you can use to achieve that `config.relative_url_root` and `application.router.default_url_options[:script_name]`.

JsRoutes v2.3.3 doesn't have support for `script_name`. I added it in current `main`: ae81df9d31e3593415108d78d08272c85730cae6

Some reading: https://github.com/rails/rails/issues/29053

I believe the thing that would do the trick for you is:

``` ruby
Rails.application.routes.draw do
  default_url_options script_name: "/apps/foo"
end

JsRoutes.setup do |c|
  c.default_url_options = { script_name: nil }
end
```


by the way the hack you are using can be improved like:

``` ruby 
class JsRoutes::Instance
  alias __spec spec
  def spec
     spec.right.right.right.right
  end
end
```

**Comment by le0pard** [comment]
or make wrapper in js:

```js
import * as routes from './routes'

const generateRoute = (name, options = {}) => routes[name].call(options).toString().replace(/^\/apps\/foo/, '')

```

**Comment by ibrykov-mdsol** [comment]
@bogdan thank you for your detailed answer!

A couple things about what you said.

> I only need to know how you define the /apps/foo namespace, weather it wraps the entirety of routes or just part of them.

Basically, all our routes are in this block
```
Rails.application.routes.draw do
  scope "/apps/foo" do
    ...
  end
end
```
(it's not exactly how we do it, there is some proprietary API involved but it does `scope` at the end of the day)

> JsRoutes v2.3.3 doesn't have support for script_name. I added it in current main

I don't think `script_name` support would solve my problem in any way. It can add more of a prefix but it cannot remove it, correct?

> by the way the hack you are using can be improved like:

The hack seems to work great and it looks significantly better, I'll use it for now.

You never commented on my idea: 
> an option to the configuration to apply a lambda/proc to all the routes so that we could granularly tweak them any way we want?

What's your opinion on that?

**Comment by ibrykov-mdsol** [comment]
@oleksii-leonov 

> or make wrapper in js:

I considered this option but it would mean a lot of updates to already existing code, conveying this way to my team and making them switch to this new helper (they will forget and I will have to rely on code reviews or start thinking about some eslint rule for that). Then, if a route name changes, there is no js/ts error that would come up with this approach (RN, js will not compile if this happens). Far from ideal.

**Comment by bogdan** [comment]
> I don't think script_name support would solve my problem in any way. It can add more of a prefix but it cannot remove it, correct?

I think you should add a prefix e.g. `/apps/foo` on backend but remove it on frontend. Again, as you didn't share the details, I assume you can replace in the routes file:

``` ruby
scop "/apps/foo" do
...
end
# with
default_url_options script_name: "/apps/foo"
```

> What's your opinion on that?

Adding an option that specifically addresses your use case but no other is bad idea. In this conversation, I am trying to guess if we can solve the problem using existing options or by introducing an option that would make a general sense.

The idea to modify the route spec feels wrong to me. Your use case is highly specific as you modify every single route the same way. Imagine the hack I proposed if it would account for every node type instead of assuming `right.right.right.right` is legit for every route.
By the way, rails never promised backward compatibility on the api of route spec object. It can break any day with no excuse.

If your route need to behave differently in different envs, it means that it need to have a parameter.

I tried the following configuration on test project and it works for me:

```
JsRoutes.setup do |c|
  c.default_url_options = { global_prefix: "/" }
end


Rails.application.routes.draw do
  default_url_options global_prefix: "apps/foo"
  scope "/*global_prefix" do
    ...
  end
end
```

I chose a long name for parameter to make sure it doesn't collide with anything.

**Comment by ibrykov-mdsol** [comment]
@bogdan, the approach with `default_url_options` actually seems to work. I was able to tweak our setup to use it. Our app works differently after it's deployed, so I'll do more testing.

There is another problem tho. With version 2.3 we now have `routes.d.ts` file (which I appreciate and welcome!). Look at what it's doing for me. `globalPrefix` is now a required parameter even though I have set it up to have a default value via `JsRoutes.setup`. Can this be fixed?

```
export const resourcePath: ((
  globalPrefix: RequiredRouteParameter,
  options?: {format?: OptionalRouteParameter} & RouteOptions
) => string) & RouteHelperExtras;
```

**Comment by bogdan** [comment]
Try this:

``` ruby
Rails.application.routes.draw do
  default_url_options global_prefix: "apps/foo"
  scope "(/*global_prefix)" do
    ...
  end
end
```

**Comment by ibrykov-mdsol** [comment]
> Try this:

Oh I see what you did there. Somehow I didn't realize these patterns work in scopes too. TIL. 

Thank you @bogdan, it was super helpful. Just like I said, I'll do more testing and maybe come back here to nag a bit more but for now I'm closing this issue!

I appreciate your help! 🙏
