### ISSUE TITLE
Put a rubygems api key into repo secrets

### ISSUE THREAD

**Issue by bogdan** [railsware/js-routes#328]
I want to automate releases of the gem with github actions: https://github.com/railsware/js-routes/blob/main/.github/workflows/release.yml#L56C39-L56C61

@le0pard we need to contact someone via a private channel so I can share the API key and put to project secrets.

**Comment by le0pard** [comment]
I don't have access, but @kovpack should have this ability

**Comment by bogdan** [comment]
@kovpack can you help? how can I contact you via a private channel?

**Comment by le0pard** [comment]
@bogdan send key to anatoliy.yevpack@railsware.com , I will ping him in slack to do update

**Comment by kovpack** [comment]
yes, please, send to my email

**Comment by kovpack** [comment]
Done
