### ISSUE TITLE
Support jQuery-style parameter arrays

### ISSUE THREAD

**Issue by dark-panda** [railsware/js-routes#76]
jQuery's `$.param` function supports parameter arrays created by `.serializeArray` as shown here: 

http://api.jquery.com/serializeArray/

```javascript
[
  {
    name: "a",
    value: "1"
  },
  {
    name: "b",
    value: "2"
  },
  {
    name: "c",
    value: "3"
  },
  {
    name: "d",
    value: "4"
  },
  {
    name: "e",
    value: "5"
  }
]
```

Running this through `$.param` creates the following:

```javascript
"a=1&b=2&c=3&d=4&e=5"
```

JsRoutes currently raises the following exception when trying a similar array:

```
Error: Url parameters should be a javascript hash
```

It would be nice if JsRoutes could support this style of parameter array. JavaScript hashes aren't ordered, hence the serialized array that jQuery provides, which does provide a specific order.

**Comment by le0pard** [comment]
Solved by https://github.com/railsware/js-routes/pull/155
