### ISSUE TITLE
The optionaly scoped restfull path get rendered wrongly if I provide the optional part.

### ISSUE THREAD

**Issue by orbanbotond** [railsware/js-routes#86]
For this route:
    scope "(/optional/:optional_id)" do
      resources :things
    end

expected: "/optional/5/things/3"
            got: "/things/3"

**Comment by graf-abolmasov** [comment]
Hello. Any updates on the issue?
This is my case. I have an Engine mounted to /my-engine. When optional params is present, everything is ok, so messages_path returns 
> /my-engine/opt/1/messages. 

However, when optional param is missing, it cuts off /my-engine prefix and returns only 
>/messages.

**Comment by le0pard** [comment]
@graf-abolmasov Bogdan already describe issue - ruby have hash and object, js have only object. What is why js routes couldn't work in the same way as rails routes in this place. He wrote proposals. But right now we dont have pull request to solve this issue.

**Comment by bogdan** [comment]
I vote for `Routes.thing_path({id: 3, _options: true)` solution. When there is a special key that indicates that the last hash is options but not serialized object.

It makes things not so convenient but at least possible. I will accept PR if any.

**Comment by bogdan** [comment]
Fixed in version 1.3.0.
